### PR TITLE
Update Urediomodel 1.0

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.8260660.
The following version(s) will be added:
  - [8260661 (version 1)](https://www.doi.org/10.5281/zenodo.8260661)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the bioimage.io CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the bioimage.io admin team member.

Maintainers: @https://github.com/OndraZelba

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by FynnBe** [comment]
Hi @OndraZelba ! Thank you for contributing this model!
Maybe something went wrong during the upload process as none of the referenced files are included in the zenodo record.

**Comment by OndraZelba** [comment]
> Hi @OndraZelba ! Thank you for contributing this model! Maybe something went wrong during the upload process as none of the referenced files are included in the zenodo record.

Hello @FynnBe, I contacted Zenodo support and they will upload manually.

**Comment by FynnBe** [comment]
> Hello @FynnBe, I contacted Zenodo support and they will upload manually.

Good 👍  I'm afraid though the issue may have been on our side rather than with zenodo. If you have any error log or if this happens again please open an issue [here](https://github.com/bioimage-io/bioimage.io/issues/new).

**Comment by OndraZelba** [comment]
> > Hello @FynnBe, I contacted Zenodo support and they will upload manually.
> 
> Good 👍 I'm afraid though the issue may have been on our side rather than with zenodo. If you have any error log or if this happens again please open an issue [here](https://github.com/bioimage-io/bioimage.io/issues/new).

Hello Fynn, the files uploaded to Zenodo now. Hopefully they are in the correct format..

**Comment by FynnBe** [comment]
> Hello Fynn, the files uploaded to Zenodo now. Hopefully they are in the correct format..

great! For a future update, please edit the existing (latest) Zenodo record for easier tracking of its versions.

**Pull request merged**
