### PR TITLE
Update 3D UNet Arabidopsis Apical Stem Cells

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6346511.
The following version(s) will be added:
  - [7697101 (version 2)](https://www.doi.org/10.5281/zenodo.7697101)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @wolny

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: https://github.com/bioimage-io/collection-bioimage-io/pull/340, https://github.com/bioimage-io/collection-bioimage-io/pull/374, https://github.com/bioimage-io/collection-bioimage-io/pull/376

### CODE REVIEW

**Comment by FynnBe** [comment]
@wolny , is this model also supposed to have more than pytorch state dict weights now?
(current error related to gh api rate limit)

**Comment by constantinpape** [comment]
All of them are supposed to have pytorch weights. I suggest we close the current PRs and block the version updates. I will double check the respective models later.

**Comment by FynnBe** [comment]
unfortunately I already merged a few passing PRs yesterday, but we can update them again, as well...

**Comment by constantinpape** [comment]
I don't think it hurts if they got merged since as far as I can see their not breaking anything; they just don't contain the updates we need.

**Pull request closed without merging**
