### PR TITLE
Update Mitochondria TOM20 artificial labelling - pix2pix

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.10366411.
The following version(s) will be added:
  - [10492722 (version from 2024-01-11)](https://www.doi.org/10.5281/zenodo.10492722)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the bioimage.io CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the bioimage.io admin team member.

Maintainers: @esgomezm

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: https://github.com/bioimage-io/collection-bioimage-io/pull/695

### CODE REVIEW

**Comment by FynnBe** [comment]
@esgomezm  why does the zenodo record also include the packaged bioimage-model.zip? 
Looks like it contains the same files as are in the record. This file duplication makes it unclear which ones were tested, etc..
I'm going to ignore the bioimageio-model.zip as our convention is to upload the files individually to zenodo to allow selective download.

back to the real issue: 

The error suggests that it is a pytorch bug:
```
terminate called after throwing an instance of 'c10::Error'
  what():  isTuple()INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1640811723911/work/aten/src/ATen/core/ivalue_inl.h":1400, please report a bug to PyTorch. Expected Tuple but got String
Exception raised from toTuple at /opt/conda/conda-bld/pytorch_1640811723911/work/aten/src/ATen/core/ivalue_inl.h:1400
```

<details>
<summary>full conda env used in CI</summary>

```
    _libgcc_mutex           0.1           conda_forge            conda-forge
    _openmp_mutex           4.5           2_kmp_llvm             conda-forge
    aom                     3.7.1         h59595ed_0             conda-forge
    bioimageio.core         0.5.11        pyhd8ed1ab_0           conda-forge
    bioimageio.spec         0.4.9.post5   pyhd8ed1ab_0           conda-forge
    blas                    2.120         mkl                    conda-forge
    blas-devel              3.9.0         20_linux64_mkl         conda-forge
    blosc                   1.21.5        h0f2a231_0             conda-forge
    brotli                  1.1.0         hd590300_1             conda-forge
    brotli-bin              1.1.0         hd590300_1             conda-forge
    brotli-python           1.1.0         py39h3d6467e_1         conda-forge
    brunsli                 0.1           h9c3ff4c_0             conda-forge
    bzip2                   1.0.8         hd590300_5             conda-forge
    c-blosc2                2.12.0        hb4ffafa_0             conda-forge
    ca-certificates         2023.11.17    hbcca054_0             conda-forge
    certifi                 2023.11.17    pyhd8ed1ab_0           conda-forge
    charls                  2.4.2         h59595ed_0             conda-forge
    charset-normalizer      3.3.2         pyhd8ed1ab_0           conda-forge
    click                   8.1.7         unix_pyh707e725_0      conda-forge
    colorama                0.4.6         pyhd8ed1ab_0           conda-forge
    cpuonly                 2.0           0                      pytorch    
    dav1d                   1.2.1         hd590300_0             conda-forge
    freetype                2.12.1        h267a509_2             conda-forge
    giflib                  5.2.1         h0b41bf4_3             conda-forge
    icu                     73.2          h59595ed_0             conda-forge
    idna                    3.6           pyhd8ed1ab_0           conda-forge
    imagecodecs             2024.1.1      py39hf9b8f0e_0         conda-forge
    imageio                 2.33.1        pyh8c1a49c_0           conda-forge
    jxrlib                  1.1           hd590300_3             conda-forge
    lcms2                   2.16          hb7c19ff_0             conda-forge
    ld_impl_linux-64        2.40          h41732ed_0             conda-forge
    lerc                    4.0.0         h27087fc_0             conda-forge
    libaec                  1.1.2         h59595ed_1             conda-forge
    libavif16               1.0.3         hef5bec9_1             conda-forge
    libblas                 3.9.0         20_linux64_mkl         conda-forge
    libbrotlicommon         1.1.0         hd590300_1             conda-forge
    libbrotlidec            1.1.0         hd590300_1             conda-forge
    libbrotlienc            1.1.0         hd590300_1             conda-forge
    libcblas                3.9.0         20_linux64_mkl         conda-forge
    libdeflate              1.19          hd590300_0             conda-forge
    libffi                  3.4.2         h7f98852_5             conda-forge
    libgcc-ng               13.2.0        h807b86a_3             conda-forge
    libgfortran-ng          13.2.0        h69a702a_3             conda-forge
    libgfortran5            13.2.0        ha4646dd_3             conda-forge
    libhwloc                2.9.3         default_h554bfaf_1009  conda-forge
    libiconv                1.17          hd590300_2             conda-forge
    libjpeg-turbo           3.0.0         hd590300_1             conda-forge
    liblapack               3.9.0         20_linux64_mkl         conda-forge
    liblapacke              3.9.0         20_linux64_mkl         conda-forge
    libnsl                  2.0.1         hd590300_0             conda-forge
    libpng                  1.6.39        h753d276_0             conda-forge
    libsqlite               3.44.2        h2797004_0             conda-forge
    libstdcxx-ng            13.2.0        h7e041cc_3             conda-forge
    libtiff                 4.6.0         ha9c0a0a_2             conda-forge
    libuuid                 2.38.1        h0b41bf4_0             conda-forge
    libuv                   1.46.0        hd590300_0             conda-forge
    libwebp-base            1.3.2         hd590300_0             conda-forge
    libxcb                  1.15          h0b41bf4_0             conda-forge
    libxcrypt               4.4.36        hd590300_1             conda-forge
    libxml2                 2.11.6        h232c23b_0             conda-forge
    libzlib                 1.2.13        hd590300_5             conda-forge
    libzopfli               1.0.3         h9c3ff4c_0             conda-forge
    llvm-openmp             17.0.6        h4dfa4b3_0             conda-forge
    lz4-c                   1.9.4         hcb278e6_0             conda-forge
    markdown-it-py          3.0.0         pyhd8ed1ab_0           conda-forge
    marshmallow             3.20.2        pyhd8ed1ab_0           conda-forge
    marshmallow-jsonschema  0.13.0        pyhd8ed1ab_0           conda-forge
    marshmallow-union       0.1.15.post1  pyhd8ed1ab_0           conda-forge
    mdurl                   0.1.2         pyhd8ed1ab_0           conda-forge
    mkl                     2023.2.0      h84fe81f_50496         conda-forge
    mkl-devel               2023.2.0      ha770c72_50496         conda-forge
    mkl-include             2023.2.0      h84fe81f_50496         conda-forge
    ncurses                 6.4           h59595ed_2             conda-forge
    numpy                   1.26.3        py39h474f0d3_0         conda-forge
    openjpeg                2.5.0         h488ebb8_3             conda-forge
    openssl                 3.2.0         hd590300_1             conda-forge
    packaging               23.2          pyhd8ed1ab_0           conda-forge
    pandas                  2.1.4         py39hddac248_0         conda-forge
    pillow                  10.2.0        py39had0adad_0         conda-forge
    pip                     23.3.2        pyhd8ed1ab_0           conda-forge
    pthread-stubs           0.4           h36c2ea0_1001          conda-forge
    pygments                2.17.2        pyhd8ed1ab_0           conda-forge
    pysocks                 1.7.1         pyha2e5f31_6           conda-forge
    python                  3.9.18        h0755675_1_cpython     conda-forge
    python-dateutil         2.8.2         pyhd8ed1ab_0           conda-forge
    python-stdnum           1.19          pyhd8ed1ab_0           conda-forge
    python-tzdata           2023.4        pyhd8ed1ab_0           conda-forge
    python_abi              3.9           4_cp39                 conda-forge
    pytorch                 1.10.2        py3.9_cpu_0            pytorch    
    pytorch-mutex           1.0           cpu                    pytorch    
    pytz                    2023.3.post1  pyhd8ed1ab_0           conda-forge
    pyyaml                  6.0.1         py39hd1e30aa_1         conda-forge
    rav1e                   0.6.6         he8a937b_2             conda-forge
    readline                8.2           h8228510_1             conda-forge
    requests                2.31.0        pyhd8ed1ab_0           conda-forge
    rich                    13.7.0        pyhd8ed1ab_0           conda-forge
    ruamel.yaml             0.18.5        py39hd1e30aa_0         conda-forge
    ruamel.yaml.clib        0.2.7         py39hd1e30aa_2         conda-forge
    setuptools              69.0.3        pyhd8ed1ab_0           conda-forge
    shellingham             1.5.4         pyhd8ed1ab_0           conda-forge
    six                     1.16.0        pyh6c4a22f_0           conda-forge
    snappy                  1.1.10        h9fff704_0             conda-forge
    svt-av1                 1.8.0         h59595ed_0             conda-forge
    tbb                     2021.11.0     h00ab1b0_0             conda-forge
    tifffile                2023.12.9     pyhd8ed1ab_0           conda-forge
    tk                      8.6.13        noxft_h4845f30_101     conda-forge
    tqdm                    4.66.1        pyhd8ed1ab_0           conda-forge
    typer                   0.9.0         pyhd8ed1ab_0           conda-forge
    typing-extensions       4.9.0         hd8ed1ab_0             conda-forge
    typing_extensions       4.9.0         pyha770c72_0           conda-forge
    tzdata                  2023d         h0c530f3_0             conda-forge
    urllib3                 2.1.0         pyhd8ed1ab_0           conda-forge
    wheel                   0.42.0        pyhd8ed1ab_0           conda-forge
    xarray                  2023.12.0     pyhd8ed1ab_0           conda-forge
    xorg-libxau             1.0.11        hd590300_0             conda-forge
    xorg-libxdmcp           1.1.3         h7f98852_0             conda-forge
    xz                      5.2.6         h166bdaf_0             conda-forge
    yaml                    0.2.5         h7f98852_2             conda-forge
    zfp                     1.0.1         h59595ed_0             conda-forge
    zlib-ng                 2.0.7         h0b41bf4_0             conda-forge
    zstd                    1.5.5         hfc55251_0             conda-forge
```
</details>

@esgomezm could you please post your working, local environment here for comparison? (`mamba list -r`)

**Comment by FynnBe** [comment]
ah, well. A trivial issue!

The collection's default pytorch version is 1.10 (which was resolved to 1.10.2), but you have 2.1.0 in your env... 
The default has been used as `pytorch_version` is not specified in the rdf.yaml. (We don't have a default in spec, but currently do allow to not specify the pytorch version. So for practical purposes the collection repo had to choose a default).

The next minor bioimageio.spec release will make `pytorch_version` a mandatory field which will prevent this issue in the future.

**Comment by esgomezm** [comment]
Hi @FynnBe!
Ok, then I'll update also the export to specify the torch version. I thought that the library was automatically testing what's the installed version. Now I see that there's a different error :D

**Comment by FynnBe** [comment]
> Hi @FynnBe! Ok, then I'll update also the export to specify the torch version. I thought that the library was automatically testing what's the installed version. Now I see that there's a different error :D

my bad, I messed up the YAML syntax of the patch...

**Comment by esgomezm** [comment]
I'm excited about seeing this one becoming green! I think this will never change xD
Screenshot 2024-01-23 at 10 45 59

**Comment by esgomezm** [comment]
passed!!!

**Pull request merged**
