### PR TITLE
Update 2D UNet Arabidopsis Apical Stem Cells

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6334881.
The following version(s) will be added:
  - 6334882

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/f6423a28-b78e-48ef-808a-6073d9518901/rdf.yaml

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by constantinpape** [comment]
The model passes now and I think this looks good. I think we should add "plantseg" to all the tags for the plantseg models though, in order to have some way to group them on the website.
What do you think @wolny? If yes, you could either update this manually by creating new versions on zenodo or we could just add it here on github.

**Comment by wolny** [comment]
That's a good point. Doing it on github should be quicker right? But where to we change it exacly?

**Comment by FynnBe** [comment]
> That's a good point. Doing it on github should be quicker right? But where to we change it exacly?

probably. Keep in mind that you'll have to specify all tags when overwriting the tags field, not just the one you want to add

**Comment by constantinpape** [comment]
> That's a good point. Doing it on github should be quicker right? But where to we change it exacly?

The easiest way for you would be to do it via zeniodo. For this you would need to create a new version of the deposit on zenodo where you only need to replace the RDF (with updated tags).

Doing it on github is only easy with write access to this repository.

So there are two options: we merge now and then one of us (@FynnBe, me) adds the plantseg tag in bulk on github.
Or you @wolny update it on zenodo before we merge.

**Comment by FynnBe** [comment]
or you make PRs for the tags from a fork ;-)

for that you can add a field `tags` to the root of resource.yaml or for the one version ('latest'). Either works

**Comment by constantinpape** [comment]
> uups, btw, I accidentally merged this one already, I suppose we can update the tags still. Just shouldn't forget about this one..
> #326

No worries, the tags are an easy fix.

**Pull request merged**
