### PR TITLE
Update filoTips default

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.8346993.
The following version(s) will be added:
  - [8346994 (version 1)](https://www.doi.org/10.5281/zenodo.8346994)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the bioimage.io CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the bioimage.io admin team member.

Maintainers: @eddin022

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by FynnBe** [comment]
Thank you for contributing @eddin022 !

The [zenodo record](https://www.doi.org/10.5281/zenodo.8346994) is missing all files linked in the rdf.yaml. 
@oeway , maybe there was an issue with [bioimage.io/upload ](https://bioimage.io/#/upload)? 

For whatever reasons the files are missing, @eddin022  please add them. Let us know if you encounter any issues using [bioimage.io/upload ](https://bioimage.io/#/upload). Note that new zenodo record versions can also be created directly at [zenodo.org](https://www.doi.org/10.5281/zenodo.8346994).

One other thing I already noticed:
- Your citation entry "Eddington C., Shwartz J., and Titus M. filoVision: using deep learning and tip markers to automate filopodia analysis." is missing a `doi` or `url` (an empty string is not valid).

**Comment by esgomezm** [comment]
@eddin022, I think you used the ZeroCostDL4Mic notebook for this one. When you run the export to the bioimage model zoo, the notebook generates a zip file with the model and all the content that @FynnBe addressed. Can you see that zip file? Could you please send us a screenshot of its content? 
Let us know if we can help you upload the model correctly :)

**Comment by eddin022** [comment]
Dear esgomezm,

Thank you for your reply. Yes, ZeroCostDL4Mic was used for this. The
screenshot is below.
I was a bit confused about the upload process. I believe I just uploaded
the .yaml file (oops!). The .zip package is what should have been uploaded
though correct?
To fix this, should I edit the upload on Zenodo or Bioimage (or both)?

Thanks again!

Regards,
Casey

[image: Screenshot 2023-10-04 at 6.11.57 PM.png]

**Comment by FynnBe** [comment]
> To fix this, should I edit the upload on Zenodo or Bioimage (or both)?

Whatever you prefer. You are updating the zenodo record either way. bioimage.io/#/upload may be more convenient to just drop the whole zip file.

I'll block this pending version 1 and look forward to see your updated version 2!

**Comment by eddin022** [comment]
Fynn,

Sorry, I'm new to the platform. Is there a way to edit the upload, or
should I just start a new upload?

Thanks again,
Casey

**Comment by FynnBe** [comment]
No worries, very happy to see that you contribute!

Either on zenodo.org or through bioimage.io you'll create another version of the record.
Each Zenodo record has a concept DOI that is fixed and each version of that record has their own version specific DOI, see https://help.zenodo.org/faq/#versioning.

To edit a record on zenodo navigate to it while being logged in and you'll see an edit button:
image

The bioimage.io/#/upload form also allows you such an update.

here in collection-bioimage-io we now know of your filoTips model and only blocked the current, first version, not the "concept" of it. So a new version will trigger a new PR.

So, yes please "edit" your upload by uploading a new version.

**Comment by eddin022** [comment]
Dear Fynn,

Thanks for the help so far! I have uploaded a new version of this model
successfully.

I'm now trying to upload my other models via bioimage.io. When trying to
upload these models, the validation passes and "OK" is available to click.
When I click "OK" I get the following error message: "Failed to find
similar items, please try it again." I couldn't find a similar error online
so I'm not sure how to fix it. I tried logging out and re-uploading, but
received the same error message.

Regards,
Casey

**Comment by FynnBe** [comment]
There is an issue with the new version you uploaded: Somehow the zenodo record holds a zip archive instead of the individual files. We currently do not support this.
Maybe @oeway already knows what's going wrong. There might be an issue with the uploader.

**Comment by oeway** [comment]
> There is an issue with the new version you uploaded: Somehow the zenodo record holds a zip archive instead of the individual files. We currently do not support this.
> Maybe @oeway already knows what's going wrong. There might be an issue with the uploader.

I haven’t looked into the uploader yet, but with the upgrade in zenodo, I doubt it will work properly.

I suggest that hold on the task and maybe take the oppotunity to migrate the uploading system to the new one. @FynnBe This however does mean that we will need to let the upload stop for a while. What do you think?

**Comment by esgomezm** [comment]
Hi @oeway and @FynnBe I have just checked and the uploader is not working at all. It does not upload any file anywhere. @oeway I agree with you that maybe it should be temporarily blocked until is solved. 

@eddin022 I apologise for all the mess. I checked your repo and I think you directly updated the zenodo version by uploading the zip file, am I right? You did as we told you and we were not very clear so, our apologies. 
Now, the content of the zip file is perfectly fine (I double-checked)! =)
We use the zip to drag and drop the content when uploading a model through the bioimage model zoo web page. If you want to **update Zenodo directly** as you did, you need to upload the files inside the zip independently (without being compressed). So all these files: Contours2InstanceSegmentation.ijm, sample_input_0.tif, README.md, sample_output_0.tif, cover.png, test_input.npy, keras_weights.hdf5, test_output.npy, per_sample_scale_range.ijm, tf_weights.zip, rdf.yaml, training_evaluation.csv. It will look like this:

Screenshot 2023-10-17 at 10 37 38

Please, update it and we will follow up!

**Comment by eddin022** [comment]
Dear all,

Ahh, okay. I have uploaded as you requested. Thanks again for the help!

Unfortunately, I think I might need more... I'm trying to upload a total of
3 additional models via bioimage.io. I click upload, login to zenodo, drag
and drop my zip file, I'm able to validate the form and the "OK" button
becomes active. However, after clicking "OK" I receive an error "Failed to
find similar items, please try it again". Is this the uploader error you
were referring to? How should I proceed with uploading the other 3 models?

Regards,
Casey

**Comment by FynnBe** [comment]
> > There is an issue with the new version you uploaded: Somehow the zenodo record holds a zip archive instead of the individual files. We currently do not support this.
> > Maybe @oeway already knows what's going wrong. There might be an issue with the uploader.
> 
> I haven’t looked into the uploader yet, but with the upgrade in zenodo, I doubt it will work properly.
> 
> I suggest that hold on the task and maybe take the oppotunity to migrate the uploading system to the new one. @FynnBe This however does mean that we will need to let the upload stop for a while. What do you think?

I wouldn't mind. The option to upload directly to zenodo is unaffected.

**Comment by FynnBe** [comment]
> How should I proceed with uploading the other 3 models?

@eddin022 Please go directly to https://zenodo.org, login there, (go to the record you want edit) and create the (new verison of the) record as laid out by @esgomezm.

**Comment by eddin022** [comment]
Fynn,

I have created a new version for the first model. I'm trying to upload 3
other models. Since they are different, my plan was to upload them
separately and I'm receiving an error message when trying to upload a new
model on bioimage.io. I'm happy to upload them directly on zenodo, but I
would also like them to be uploaded on bioimage.io if possible. If I upload
them directly on zenodo, can we later have them available on bioimage.io as
well?

Casey

**Comment by FynnBe** [comment]
> I'm happy to upload them directly on zenodo, but I
would also like them to be uploaded on bioimage.io if possible. If I upload
them directly on zenodo, can we later have them available on bioimage.io as
well?

Dear Casey, apologies for our unclear communication -- we've been talking amongst ourselves so much it is hard sometimes to imagine a fresh pair of eyes on the matter.
As we currently use zenodo.org as our storage space for all models, all the bioimage.io uplaoder would do is upload to zenodo.org in your name and make sure the keyword "bioimage.io" is present.
Through this keyword our bot detects relevant zenodo records and opens a Pull Request (PR) like this one.
 
The upload to zenodo.org via bioimage.io has caused confusion before; therefore we decided to change this part in the near future. For now, please uplaod manually to zenodo.org and make sure to tag your recrods with the "bioimage.io" keyword. Once a PR such as this is merged they will show up on bioimage.io !

**Comment by eddin022** [comment]
Got it, thanks!

Casey

**Comment by esgomezm** [comment]
@eddin022 just to double confirm with you:
Each of your new models should be in a completely new Zenodo repository. So, each Zenodo repository (same as for papers, code or whatever), represents "A MODEL". If you change the model (as you did until now to update it or correct the format), then you need to update its corresponding Zenodo repository with a new version. 
If you want to upload a *new model*, then you need to create a new repository by clicking on + (new upload) in Zenodo. Once you create it, make sure as @FynnBe said, that you add the bioimage.io as a community. See the shots below
Hope it's getting easy!

* New upload to create a new zenodo repository.
Screenshot 2023-10-18 at 11 46 41
* Connect with the bioimage.io
Screenshot 2023-10-18 at 11 46 56

**Comment by eddin022** [comment]
Got it. Thanks. I think the most recent issue was not being able to upload
new models (not versions but different models) via bioimage.io recently. I
was able to upload via zenodo directly though and I selected the bioimage.io
community for each one.

Casey

**Comment by eddin022** [comment]
Dear all,

I hope you have been well.

I uploaded a total of 3 models and 2 datasets directly to Zenodo (listing
bioimage.io as the community) mid-Sept and mid-Oct. 1 model has been
accepted, but the rest are in review. Is there anything else that needs to
be done for them to be accepted?

Thanks again!

Casey

**Comment by FynnBe** [comment]
Dear Casey,
I'm working on fixing the issues in https://github.com/bioimage-io/collection-bioimage-io/pull/656
And I haven't seen the datasets you're mentioning. Would you be so kind to share the zenodo links or DOIs of the resources you want to contribute, then I'll check each one myself.

I'm sorry for the delay and inconvenience. We are working on a series of internal updates and recently Zenodo changes their API which threw us a bit into turmoil.

**Comment by eddin022** [comment]
Fynn,

No problem. Below are the DOIs:

10.5281/zenodo.10019447
10.5281/zenodo.10015653
10.5281/zenodo.10015613
10.5281/zenodo.8356811

Casey

**Pull request merged**
