### PR TITLE
Update CVD graphene SEM image segmentation

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.7052800.
The following version(s) will be added:
  - [7052801 (version 1)](https://www.doi.org/10.5281/zenodo.7052801)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [x] The tags are complete and describe the model
  - [x] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [x] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @AagamShah97

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by AagamShah97** [comment]
@esgomezm

**Comment by esgomezm** [comment]
Hey @AagamShah97 
Please, update the rdf file by removing the attachment item pointing to the jupyter notebook. Then, the procedure to follow is the next one (@oeway correct me if I'm wrong please):
- Upload the new model again. It should suggest to update this model. Click on update. 
- In this pull request, we would include the new version manually if it's not automatically updated.

Thank you!

**Comment by AagamShah97** [comment]
@esgomezm I updated the RDF file and uploaded the model again, but no new pull request was created, and nor did it suggest to update the model. This is the link to the updated model on Zenodo: https://doi.org/10.5281/zenodo.7053391. How shall I proceed from here?

Thanks!

**Comment by esgomezm** [comment]
Hi @AagamShah97 

It created this new pull request: https://github.com/bioimage-io/collection-bioimage-io/pull/477
I will keep the discussion there if you don't mind and close this pull request. I can see that there are still some errors that need to be cleared. Probably you can just update the zenodo repository. I will give you some instructions in a second

**Pull request closed without merging**
