### PR TITLE
Update Small Extracellular Vesicle TEM Segmentation (Fully Residual U-Net)

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6559474.
The following version(s) will be added:
  - [6559475 (version 1)](https://www.doi.org/10.5281/zenodo.6559475)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @esgomezm

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by FynnBe** [comment]
required tensorflow (version) is not available through conda...
```
Looking for: ['bioimageio.core', "tensorflow[version='>=1.12,<1.13']"]
  
  
  Encountered problems while solving:
    - package tensorflow-1.12.0-gpu_py27h956c076_0 requires tensorflow-base ==1.12.0 gpu_py27h8e0ae2d_0, but none of the providers can be installed
    
```

**Comment by FynnBe** [comment]
should we fetch tensorflow always with pip or just as a fallback?
@constantinpape what do you think?

**Comment by constantinpape** [comment]
> @constantinpape what do you think?

Do what you think is right here, I currently don't have the bandwidth to deal with any of the day to day here.

(On a general note, we need to be aware that support for tf 1 is a huge technical debt...)

**Comment by FynnBe** [comment]
before #496 is resolves we can avoid this issue by providing a conda environment.yaml file that get's tensorflow with pip:

something like:

```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - tensorflow=1.12
```

**Comment by FynnBe** [comment]
interestingly tf 1.12 is not available via pip either (anymore)
```
Could not find a version that satisfies the requirement tensorflow<1.13,>=1.12 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2)
```
I suggest we use tf 1.13 if 1.12 is specified... will make another separate PR to change this.

**Comment by esgomezm** [comment]
I think this version of the model is not updated. Can I close the PR and try uploading it again? Back in the time there was a problem with updating the rdf file

**Comment by FynnBe** [comment]
with protobuf pinned this model is ready to be merged!!
just checking with @esgomezm as this model has been pending for a while... any updates?
Otherwise go ahead and merge ;-)

**Comment by FynnBe** [comment]
> I think this version of the model is not updated. Can I close the PR and try uploading it again? Back in the time there was a problem with updating the rdf file

there is no updated version yet on zenodo: https://zenodo.org/record/6559475#.Y2T_LHbMJjE

**Comment by esgomezm** [comment]
no sorry, there was another one in my zenodo account. I think it's because I tried to upload again to solve of the existing problems. I will merge this and let's see if there is no new PR coming :D

**Pull request merged**
