### PR TITLE
Update NIH 3T3 Fibroblast Phase Contrast Segmentation (Usiigaci-Mask R-CNN)

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.7139022.
The following version(s) will be added:
  - [7139023 (version 1)](https://www.doi.org/10.5281/zenodo.7139023)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @deepimagej

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by esgomezm** [comment]
Hey @lmoyasans is this the model you are referring to? I do not find any other. If it's that one, then it is from the deepImageJ repo and that's why you cannot update it like this. Please, let me know and I will remove that one

**Comment by FynnBe** [comment]
after discussion with @carlosuc3m :
to fix this model:
 1. [ ] input shape description needs to match test input

**Comment by carlosuc3m** [comment]
@lmoyasans we need to change the input npy array to an array compliant with the validator. The input npy array should have the following dimensions: [1, 1024, 1024, 3].
This is the image after preprocessing. In order to do so, run Usiifaci model in verbose (or debuf mode, I cannot remember what is the name right now) and save the image that is produced after preprocessing. Then save that image and convert it with python into a np array with the mentioned axes order.
After that upload it to the correspondig zenodo folder.
The validation should then pass

**Comment by esgomezm** [comment]
please please, @lmoyasans, besides the bug @carlosuc3m speaks about, do not forget to upload to zenodo the zip file with the model so we can also download it automatically from Zenodo through the link. For this, you need to 
- Add the zip inside the zip file you use to upload a model to the BMZ
- In the yaml file, there's a field called `download_url` where you can write the relative path to the file and the uploader will create the absolute path (e.g., `download_url: ./my_bmz_model.zip`) (This is a functionality that @FynnBe added a while ago, it's somewhere discussed in the issues). 
- This zip file SHOULD NOT APPEAR in the attachments.

**Pull request merged**
