### PR TITLE
Update 2D UNet Arabidopsis Ovules

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6334383.
The following version(s) will be added:
  - 6334384

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/63b44f05-a187-4fc9-81c8-c4568535531b/rdf.yaml

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by constantinpape** [comment]
The test fails with:
```
  'error': "module 'bioimageio.core.resource_io.nodes' has no attribute 'ImportableSourceFile'"
```
Here's the `weight` definition in the preview rdf:
```
weights:
  pytorch_state_dict:
    architecture: https://zenodo.org/api/files/63b44f05-a187-4fc9-81c8-c4568535531b/unet.py:UNet2D
    architecture_sha256: 2da9f7149e144b63fee715fb8fe5154e96bf9aa230d176c91e923d528ef0c4e1
    dependencies: conda:https://zenodo.org/api/files/63b44f05-a187-4fc9-81c8-c4568535531b/environment.yaml
    kwargs:
      f_maps: 64
      final_sigmoid: true
      in_channels: 1
      is_segmentation: true
      layer_order: gcr
      num_groups: 8
      out_channels: 1
      testing: true
```
@FynnBe is there maybe some issue in bioimageio.core that leads to an issue when `architecture` is  an URL?

**Comment by constantinpape** [comment]
@wolny please add yourself to the maintainer fields for the next models you upload, so that you get notifications about your models.
(But for now let's wait with uploading more models till we figure out what's wrong here)

**Comment by FynnBe** [comment]
> @FynnBe is there maybe some issue in bioimageio.core that leads to an issue when architecture is an URL?

no this is a bug introduced with the partner field update (as core is now not resolving all URIs). It should actually resolve `architecture`, so there might be another bug... I'll fix it asap (if the second bug also exists this might need a fix in spec)

**Comment by constantinpape** [comment]
> no this is a bug introduced with the partner field update (as core is now not resolving all URIs). It should actually resolve `architecture`, so there might be another bug... I'll fix it asap (if the second bug also exists this might need a fix in spec)

Ok, please add a test while you're on it.

**Comment by wolny** [comment]
> @wolny please add yourself to the maintainer fields for the next models you upload, so that you get notifications about your models. (But for now let's wait with uploading more models till we figure out what's wrong here)

I'm pretty sure I filled in the maintainer field during the upload. Or should I also specify it in the rdf?

**Comment by oeway** [comment]
> > @wolny please add yourself to the maintainer fields for the next models you upload, so that you get notifications about your models. (But for now let's wait with uploading more models till we figure out what's wrong here)
> 
> I'm pretty sure I filled in the maintainer field during the upload. Or should I also specify it in the rdf?

I guess there is a bug with the uploader in the website, I will look into it when I got some bandwidth. For now, please add it in the rdf before you upload it.

**Pull request merged**
