### PR TITLE
Fix BioEngine Apps RDF rendering

### PR DESCRIPTION
**Pull request by oeway**
This PR fixes the priority of information when generating the rdf for the bioengine apps. This part has been broken for several weeks now, we need to fix it as soon as possible. I will merge soon.

cc @FynnBe

### CODE REVIEW

**Comment by oeway** [comment]
@FynnBe Help! I tested it locally and now it can produce the right RDF but somehow the summary file remains the same, do we need some extra procedure to trigger it or I missed something?

**Comment by FynnBe** [comment]
this PR is counter-productive. Now the parsed imjoy plugin is overwriting the version info. thus overwriting any field in the `resource.yaml` is not possible anymore. 
Please don't merge unreviewed PRs within hours if it is not a trivial change.

If the partner collection has not changed one can reset its hash, e.g. https://github.com/bioimage-io/collection-bioimage-io/commit/558bcf0222f3249d06b5cdf8feff971b8ec5ad07 . Now on the next "update collection" run this partner's collection will be processed despite no changes...

**Comment by oeway** [comment]
> this PR is counter-productive. Now the parsed imjoy plugin is overwriting the version info. thus overwriting any field in the `resource.yaml` is not possible anymore. Please don't merge unreviewed PRs within hours if it is not a trivial change.

Sorry but it has been broken for weeks and not get fixed, I need this now to test the apps. IMO, having the overwriting feature from `resource.yaml` is much less important than get the apps working on the website. I'd prefer something working on the website rather than have the nice technical features or a more correct implementation.

We can always improve with more PRs, but the features that breaking the website should always take priority.

> 
> If the partner collection has not changed one can reset its hash, e.g. [558bcf0](https://github.com/bioimage-io/collection-bioimage-io/commit/558bcf0222f3249d06b5cdf8feff971b8ec5ad07) . Now on the next "update collection" run this partner's collection will be processed despite no changes...

I don't understand, shouldn't this be automatic? How can we trigger this?

**Comment by oeway** [comment]
@FynnBe It looks like it didn't work, even after you triggering it manually: https://github.com/bioimage-io/collection-bioimage-io/blob/558bcf0222f3249d06b5cdf8feff971b8ec5ad07/rdf.yaml#L1191

**Comment by FynnBe** [comment]
I made this my number one priority now... this needs fixes in some other places, too...

**Comment by oeway** [comment]
> I made this my number one priority now... this needs fixes in some other places, too...

Great! Thanks!  Even if you only have a quick hot fix, please do that now and you can implement a better version later. I really need this to work for testing the apps! I was doing a live demo earlier today and cannot get the apps working ;)

The repo is getting so complex now with all these caching etc. you will need to explain to me again one day ;) Or perhaps document it somewhere to make sure more people understand this. It will get the code review process faster, otherwise I would go for the agile way of "hot fixing first then improve" model .

**Comment by FynnBe** [comment]
After getting a bit burnt by the hot fix, it should now work as expected awaiting a cooling clean-up for proper handling of the imjoy plugins as we discussed.

**Comment by oeway** [comment]
> 

Sounds good! I didn't mean to pressure you, but if the hot fix is the thing that get you charged for the long standing issue, I am happy ;) Thanks a lot!

**Pull request merged**
