### PR TITLE
Update bioimageio_model

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6326366.
The following version(s) will be added:
  - 6334698

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/df674d68-b670-4153-b1fc-de812664f954/rdf.yaml

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: https://github.com/bioimage-io/collection-bioimage-io/pull/321

### CODE REVIEW

**Comment by constantinpape** [comment]
Now it fails with
```
 [{'error': 'Conda environment yaml file not found: '
           'dist/dynamic_validation_artifact/static_validation_artifact/10.5281/zenodo.6326366/6334698/conda_env_tensorflow_saved_model_bundle.yaml',
  'id': 'validation_summary_tensorflow_saved_model_bundle',
  'name': 'install test environment',
  'status': 'failed'}]
  ```
  Not sure why, the requirements file looks good to me: https://zenodo.org/record/6334698/files/requirements.txt?download=1

**Comment by FynnBe** [comment]
pip error from the log: ` ERROR: No matching distribution found for tensorflow<2.0,>=1.15`

**Comment by constantinpape** [comment]
I just tried locally and it works perfectly fine...
Which python version are we trying this with? I think it only works for python 3.7

**Comment by uschmidt83** [comment]
> tensorflow<2.0,>=1.15

Are you modifying the tensorflow version requirements, because the export from StarDist should have given `tensorflow>=1.15,<1.16`?

**Comment by FynnBe** [comment]
this is the env description generated:
```yaml
channels: [conda-forge, defaults]
dependencies:
- bioimageio.core
- pip
- pip: ['tensorflow>=1.15,<2.0', csbdeep>=0.6.3, scikit-image, numba, '']
name: '6334698'
```

**Comment by uschmidt83** [comment]
> I just modified this by hand now for testing; `tensorflow>=1.15,<1.16` and `>=1.15,<2.0` should be equivalent.

Sure, it's equivalent in this case, I was just confused where this came from.

**Pull request merged**
