### PR TITLE
add icy info to include it as a partner

### PR DESCRIPTION
**Pull request by carlosuc3m**

### CODE REVIEW

**Comment by carlosuc3m** [comment]
This is the pull request to add the Icy as a partner to the BioImage.io.
The bioimage.io resources repository for Icy is hosted in [Gitlab instead of Github](https://gitlab.pasteur.fr/bia/icy-bioimage-io-resources), is that the cause of the error?
Also the CI is missing at the moment, do we need a CI before any model to check the [collections.yaml of Icy](https://gitlab.pasteur.fr/bia/icy-bioimage-io-resources/-/blob/main/collection.yaml)?

**Comment by FynnBe** [comment]
> do we need a CI before any model to check the [collections.yaml of Icy](https://gitlab.pasteur.fr/bia/icy-bioimage-io-resources/-/blob/main/collection.yaml)?

CI to generate test summaries as a partner is optional.
I would highly recommend to add a CI to validate the icy collection itself though.
As a reference here is the ilastik validation workflow: https://github.com/ilastik/bioimage-io-resources/blob/main/.github/workflows/validate_ilastik_collection.yaml

Currently we do assume all partner collections are hosted on GitHub. Of course we should allow gitlab hosted collections as well. This is not yet supported though (needs update to https://github.com/bioimage-io/collection-bioimage-io/blob/061efb99699f1b25553ff3c5c287087642f63654/scripts/utils.py#L109)

**Comment by carlosuc3m** [comment]
I have created a temporary repo inside the bioimage-io organization and the tests seem to pass. Is it fine?
I will now add the test that @FynnBe suggested

**Comment by carlosuc3m** [comment]
Just added the Icy collection validator https://github.com/bioimage-io/icy-bioimage-io/commit/1f7a1e6e63bf818c536d268e15b166f798296aed

**Comment by oeway** [comment]
> I have created a temporary repo inside the bioimage-io organization and the tests seem to pass. Is it fine? I will now add the test that @FynnBe suggested

I would suggest hosting the repo under the icy organization.

**Comment by constantinpape** [comment]
@FynnBe we are in principle very happy that Icy joins (just discussed this in the meeting), so feel free to merge this as soon as its fine from the technical side.

**Comment by oeway** [comment]
@carlosuc3m To avoid CORS issues etc, could you place the logos under the same repo (instead of link to gitlab?): https://gitlab.pasteur.fr/bia/icy/-/raw/master/src/main/resources/image/logo.png

And also change uri_root to the raw link of github repo.

Thanks!

**Review by FynnBe — APPROVED** [review]

**Comment by FynnBe** [comment]
welcome Icy!
image

**Comment by oeway** [comment]
Thanks for making it happen!

@carlosuc3m For the next steps, could you please still see if we can move the repo to the icy organization? And make another PR to update URL later?

**Pull request merged**
