### PR TITLE
Update bioimageio_model

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6326366.
The following version(s) will be added:
  - 6326367

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/7d28f5af-90df-4219-af60-0a00045f4f0f/rdf.yaml

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by constantinpape** [comment]
@FynnBe do you have any idea why the tests fail? `bioimageio test-model` works for me locally.

**Comment by FynnBe** [comment]
great to see the stardist model joining!
@uschmidt83 @constantinpape I'm not sure why the dynamic test is failing, in the artifacts I find this conda env:
```yaml
channels: [conda-forge, defaults]
dependencies:
- bioimageio.core
- pip
- pip: [tensorflow, csbdeep>=0.6.3, scikit-image, numba]
name: '6326367'

```
Although in the rdf.yaml `tensorflow_version` is specified it is not fixed in this environment, so it looks like an issue on our side...

**Comment by constantinpape** [comment]
fyi @FynnBe I am trying uploading the StarDist models, please don't merge yet, even if tests pass

**Comment by uschmidt83** [comment]
> `- pip: [tensorflow, csbdeep>=0.6.3, scikit-image, numba]`

> Although in the rdf.yaml `tensorflow_version` is specified it is not fixed in this environment, so it looks like an issue on our side...

We don't specify the tensorflow version for the requirements (see [code](https://github.com/stardist/stardist/blob/0d9dffbb6b010e0802e0a1267b8fd60b7f6838cf/stardist/bioimageio_utils.py#L72-L78)), should we?

**Comment by uschmidt83** [comment]
I just looked at the [Zenodo entry](https://doi.org/10.5281/zenodo.6326367). Can we update the metadata there later on?

**Comment by uschmidt83** [comment]
I downloaded the [preview](https://github.com/bioimage-io/collection-bioimage-io/suites/5527552726/artifacts/177529142) from above and there seems to be a bug in the `rdf.yaml` related to `null` entries.

In the original `rdf.yaml` (exported by StarDist):

```yaml
config:
  stardist:
    config:
      net_input_shape: [null, null, 3]
```

In the `rdf.yaml` (from the preview):

```yaml
config:
  stardist:
    config:
      net_input_shape:
      - 
      - 
      - 3
```

**Comment by oeway** [comment]
> I just looked at the [Zenodo entry](https://doi.org/10.5281/zenodo.6326367). Can we update the metadata (and files) there later on?

Yes, you can also update it on zenodo directly, but keep in mind that what really matters is the content in the rdf.yaml file. For example, to change the name, you need to change the metadata in zenodo, but also update the corresponding field in the rdf.yaml file, then create a new version and re-upload the file.

Once this is accepted, you should find the model listed at bioimage.io, and on the model card, you should find an edit button, there you can also update the model + metadata so you don't need to do it via zenodo.

**Comment by uschmidt83** [comment]
> BTW, @uschmidt83 would you mind the change the model name to a more informative one instead of bioimageio_model? You can find many examples at bioimage.io.

Do you mean for *a)* the [specific model](https://doi.org/10.5281/zenodo.6326367) that this PR here is about, or *b)* in general in our export function in StarDist?

*a)*
I don't have access to change the model (I think @constantinpape uploaded it).

*b)*
Which default model name do you suggest?

**Comment by FynnBe** [comment]
> I downloaded the [preview](https://github.com/bioimage-io/collection-bioimage-io/suites/5527552726/artifacts/177529142) from above and there seems to be a bug in the rdf.yaml related to null entries.

I get `null`s back:

```
>>> from ruamel.yaml import YAML
>>> yaml = YAML(typ='safe')
>>> s = '''config:
...   stardist:
...     config:
...       net_input_shape:
...       -
...       -
...       - 3'''
>>> yaml.load(s)
{'config': {'stardist': {'config': {'net_input_shape': [None, None, 3]}}}}
>>>
```
I suppose explicit `null` values would be good anyway though

**Comment by oeway** [comment]
> Do you mean for a) the [specific model](https://doi.org/10.5281/zenodo.6326367) that this PR here is about, or b) in general in our export function in StarDist?

I meant this particular PR. However, it doesn't matter if this model is just for testing. It matters only if we want to merge it and show it on the website.

> Which default model name do you suggest?

For the export function, it does make sense to have a better default model name in the package. I would at least mention `Stardist` in the name, something like `Stardist Segmentation`.

**Comment by FynnBe** [comment]
> Can we update the metadata (and files) there later on?

yes, this will create a new version for that record

**Comment by constantinpape** [comment]
Hi all, 

thanks for looking into it; I don't have much time today, so just briefly for the points I can answer:

> We don't specify the tensorflow version for the requirements (see [code](https://github.com/stardist/stardist/blob/0d9dffbb6b010e0802e0a1267b8fd60b7f6838cf/stardist/bioimageio_utils.py#L72-L78)), should we?

Yes, that would be good.

Regarding updating of model and metadata: this is fairly easy and there are two options: 1.) update the model on zenodo;, this will add a new version to the zenodo entry and also trigger a new PR here to display the updated version from zenodo on the website. 2.) change metadata directly in this repository, which can over-ride the data from zenodo.
Let's not worry about the second option for now though, I think this is a bit confusing for most contributors (but it's very helpful for the core team). 1.) can also be done through bioimage.io using the edit functionality, as @oeway already mentioned.

For this particular model  we still need to decide if we want it on the website at all; I will follow up on this with @uschmidt83 next week. If yes, I would like to document editing a model through the website, similar to https://github.com/bioimage-io/collection-bioimage-io#uploading-models-via-bioimageio.

In any case, we need to figure out what the issue with the CI is here in order to move forward with adding stardist models.
In the meantime we can already gather other issues with the metadata, which also need to be fixed:
- the model name, my suggestion would be something like StardistHENucleiSegmentation; but I am very open for other suggestions
- Serializing `null`: https://github.com/bioimage-io/collection-bioimage-io/pull/321#issuecomment-1059055463. (Needs to be fixed in bioimageio core or spec)
- anything else?

**Comment by uschmidt83** [comment]
> > We don't specify the tensorflow version for the requirements (see [code](https://github.com/stardist/stardist/blob/0d9dffbb6b010e0802e0a1267b8fd60b7f6838cf/stardist/bioimageio_utils.py#L72-L78)), should we?
> 
> Yes, that would be good.

What are semantics of the tensorflow version?
Is this a possible version that is known to work, or does this mean that only this version of tensorflow is approved?

**Comment by uschmidt83** [comment]
> > Which default model name do you suggest?
> 
> For the export function, it does make sense to have a better default model name in the package. I would at least mention `Stardist` in the name, something like `Stardist Segmentation`.

I've now changed the default to use the name of the StarDist model (folder name): https://github.com/stardist/stardist/pull/184/commits/d954f9816f05dfd40848ff8ced1920a2c5b00e4c

**Comment by uschmidt83** [comment]
I get the feeling that delaying the new StarDist release a few more hours/days makes sense before we figure things out here, especially regarding the tensorflow version requirements.

**Comment by FynnBe** [comment]
> What are semantics of the tensorflow version?
Is this a possible version that is known to work, or does this mean that only this version of tensorflow is approved?

Ultimately every consumer software can decide this for themselves. From the bioimage.io perspective it's definitely "version that is known to work," as this environment is used to test the model

**Comment by constantinpape** [comment]
> I get the feeling that delaying the new StarDist release a few more hours/days makes sense before we figure things out here, especially regarding the tensorflow version requirements.

I agree. 

W.r.t the tensorflow version: from my experience it's best to pin it to a specific minor version range, e.g. `tensorflow >=1.14,<1.15` if you want a tf 1.14. Pinning it to the patch version is not a good idea because this often can't be resolved properly by conda / pip

**Comment by uschmidt83** [comment]
> W.r.t the tensorflow version: from my experience it's best to pin it to a specific minor version range, e.g. `tensorflow >=1.14,<1.15` if you want a tf 1.14.

Ok, I did that: https://github.com/stardist/stardist/commit/ec7c8a2157ced84e523b545bf9a4ab7f9d2d282e

**Comment by constantinpape** [comment]
> @uschmidt83 could you please upload an updated version?
> 
> I will block the current version and merge this PR, so the updated version will be picked up and open a new PR...

I have to do this since I uploaded the model. I am on it.

**Comment by uschmidt83** [comment]
> @uschmidt83 could you please upload an updated version?

I don't know what I am supposed to do. I haven't uploaded the current model (I think @constantinpape did) and don't know how to update it (let alone have the rights to do it).

**Comment by constantinpape** [comment]
@FynnBe here's the new version with pinned tf: https://zenodo.org/record/6334698.
I don't think there will be an automatic PR, since I had to do the update through zenodo (the model is not on bioimage.io yet, so I couldn't use the update functionality there).
Can you make a PR to add it?

**Pull request merged**
