### PR TITLE
add update_collection_validation.py

### PR DESCRIPTION
**Pull request by FynnBe**
start the CI with bioimageio.spec validation and simple yaml output cache

### CODE REVIEW

**Comment by FynnBe** [comment]
tested with a local copy of [`gh-pages/rdf.yaml`](https://github.com/bioimage-io/collection-bioimage-io/blob/gh-pages/rdf.yaml) I get

```yaml
10.5072/zenodo.849032,3.8.10,0.3.2post0,None:
  errors:
    authors:
      0:
        name: [Not a valid string.]
    id: [Unknown field.]
    rdf_file: [Unknown field.]
  source: https://sandbox.zenodo.org/api/files/472b09aa-f70b-48e9-b836-6ab560e3b70c/model.yaml
10.5072/zenodo.849110,3.8.10,0.3.2post0,None:
  errors:
    documentation: ['Invalid suffix (https:\github.com\HenriquesLab\ZeroCostDL4Mic\wiki):
        Replacement index 0 out of range for positional args tuple', 'Invalid as_posix
        (https:\github.com\HenriquesLab\ZeroCostDL4Mic\wiki): expected local, relative
        file path.']
    inputs:
      0:
        data_range: [Not a valid tuple.]
        preprocessing:
          0:

...

10.5072/zenodo.872860,3.8.10,0.3.2post0,None:
  errors: []
  source: https://sandbox.zenodo.org/api/files/a6e1b0c5-bcad-4b52-933e-13c36283d93a/rdf.yaml
10.5072/zenodo.872914,3.8.10,0.3.2post0,None:
  errors: []
  source: https://sandbox.zenodo.org/api/files/406bdb5a-4dad-48cc-ae9a-d61f737d7de9/rdf.yaml
10.5072/zenodo.872916,3.8.10,0.3.2post0,None:
  errors: []
  source: https://sandbox.zenodo.org/api/files/c28391fb-4935-4a76-951f-f6910dae8fbd/rdf.yaml

....
```


todo:
 - [ ] some CI env fixes ('conda activate'??)

**Comment by FynnBe** [comment]
to develop this using yaml (or json) as validation cache should be fine. Soon we might want to look into something more appropriate to cope with a growing model zoo. Maybe sqlite could already be sufficient?

**Comment by oeway** [comment]
> to develop this using yaml (or json) as validation cache should be fine. Soon we might want to look into something more appropriate to cope with a growing model zoo. Maybe sqlite could already be sufficient?

Let's don't worry about caching right now, at least for spec validation, it's fast enough so we don't need caching. 

For the model runner testing, I would do that from the runner itself. Implementing caching need very careful consideration (e.g. we need to consider RDF change, model runner change etc.), it will often make debugging much harder, we typically don't want side effects e.g. when running CI multiple times.

**Comment by FynnBe** [comment]
> For the model runner testing, I would do that from the runner itself. Implementing caching need very careful consideration (e.g. we need to consider RDF change, model runner change etc.), it will often make debugging much harder, we typically don't want side effects e.g. when running CI multiple times.

Yes, exactly, that's why I key the results by :
> 10.5072/zenodo.872916,3.8.10,0.3.2post0,None:

id, python version, bioimageio.spec version, bioimageio.core version.
Of course we can adapt fhe format of how we save it here, this is just one possibilty. Maybe we should decide if we even need a test matrix or if a fixed combination will do. What combinations should we check?

**Comment by FynnBe** [comment]
> Let's don't worry about caching right now, at least for spec validation, it's fast enough so we don't need caching.

I would already cache but stick with the simple output format as the caching by id,python-version, etc is trivial and already implemented. ok?

**Comment by oeway** [comment]
> > Let's don't worry about caching right now, at least for spec validation, it's fast enough so we don't need caching.
> 
> I would already cache but stick with the simple output format as the caching by id,python-version, etc is trivial and already implemented. ok?

Well, the problem is that the caching can easily go wrong, for example, in some cases, github actions itself can upgrade sometimes and cause tests to fail, or sometime you would really want to trigger a complete re-run of all tests. Having the caching layer will just make our life harder, in some sense it defeat the purpose of CI. On the other hand, all the stuff we are doing are changing rather quickly, so not sure the caching will help a lot.

I think in general, caching means skip some tests and will for sure make the tests less reliable.  And you can always do selective testing for a specific model locally while developing it.

Keep in mind that each job in Github action can run up to 6 hours, I would rather wait for an hour to test all the models so we don't have to be very careful with the design of caching mechanism. Later, we can have a self-hosted CI runner with GPU, the run time can reduce a lot by then.

If we really want to do caching, I would perhaps use some dedicated libraries such as `joblib`.

**Comment by FynnBe** [comment]
good points. let's drop the caching for now and add it later when things are more stable

**Comment by FynnBe** [comment]
right now tests might only fail due to the missing current conda package for bioimageio.spec.... let's make another small post release!

**Pull request merged**
