### PR TITLE
Update PlatynereisEMcellsSegmentationBoundaryModel

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6028280.
The following version(s) will be added:
  - 10.5281/zenodo.6028281

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/9a4c6150-10d1-4c82-9305-8ac21bc435b5/rdf.yaml

The corresponding deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.6028280)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @constantinpape

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Edit the current resource.yaml and mark the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Merge this PR for now, wait until the CI on the main branch to complete. It should detect the new versions and create another PR for the new version. You can take it from there instead.

### CODE REVIEW

**Comment by oeway** [comment]
@constantinpape Is this ready to merge? Same question for other PRs which are passed.

**Comment by constantinpape** [comment]
I was waiting for @FynnBe to update the main CI, since I am not sure if it's currently working.

**Comment by FynnBe** [comment]
> I was waiting for @FynnBe to update the main CI, since I am not sure if it's currently working.

the changes in the main ci are somewhat pending on https://github.com/bioimage-io/bioimage.io/issues/237

**Comment by oeway** [comment]
> > I was waiting for @FynnBe to update the main CI, since I am not sure if it's currently working.
> 
> the changes in the main ci are somewhat pending on [bioimage-io/bioimage.io#237](https://github.com/bioimage-io/bioimage.io/issues/237)

Hmm, not sure if we need to stop merging items for the coming changes in the main CI, because this is the production repo which suppose to work and we can test the new features in @FynnBe 's forked repo independently as I understand.

The version_id thing as I see now requires more considerations in the design and time to test, ideally we should split the big PR into smaller ones to make it easier to test.

**Comment by FynnBe** [comment]
> ideally we should split the big PR into smaller ones to make it easier to test.

I have one linear main branch on my fork, no neatly separated feature branches. It's was just not that stable yet.
I think we should be fine with merging promising auto-update PRs here in the main repo. we'll have to adapt the version_id's in the collection folder anyway and also double check the already merged resources again...

**Pull request merged**
