### PR TITLE
Update HPA Bestfitting InceptionV3

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.5910854.
The following version(s) will be added:
  - 10.5281/zenodo.5911832

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/c8028ef3-de08-459c-b88a-2f0bfd11485b/rdf.yaml

The corresponding deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5910854)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Edit the current resource.yaml and mark the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Merge this PR for now, wait until the CI on the main branch to complete. It should detect the new versions and create another PR for the new version. You can take it from there instead.

### CODE REVIEW

**Comment by constantinpape** [comment]
This now fails due to very minor differences in the model test:
```
Run python scripts/check_validation_passed.py artifacts
{'validation_summary_onnx': {'error': 'Output and expected output disagree:\n'
                                      ' \n'
                                      'Arrays are not almost equal to 4 '
                                      'decimals\n'
                                      '\n'
                                      'Mismatched elements: 159 / 2048 '
                                      '(7.76%)\n'
                                      'Max absolute difference: 0.00132132\n'
                                      'Max relative difference: 0.08016495\n'
                                      ' x: array([[0.0214, 0.3054, 0.0507, '
                                      '..., 0.4618, 0.0332, 0.0118]],\n'
                                      '      dtype=float32)\n'
                                      ' y: array([[0.0214, 0.3055, 0.0507, '
                                      '..., 0.4618, 0.0332, 0.0118]],\n'
                                      '      dtype=float32)',
                             'name': 'reproduced test outputs from test inputs',
                             'traceback': None},
 'validation_summary_torchscript': {'error': 'Output and expected output '
                                             'disagree:\n'
                                             ' \n'
                                             'Arrays are not almost equal to 4 '
                                             'decimals\n'
                                             '\n'
                                             'Mismatched elements: 159 / 2048 '
                                             '(7.76%)\n'
                                             'Max absolute difference: '
                                             '0.00132108\n'
                                             'Max relative difference: '
                                             '0.08019311\n'
                                             ' x: array([[0.0214, 0.3054, '
                                             '0.0507, ..., 0.4618, 0.0332, '
                                             '0.0118]],\n'
                                             '      dtype=float32)\n'
                                             ' y: array([[0.0214, 0.3055, '
                                             '0.0507, ..., 0.4618, 0.0332, '
                                             '0.0118]],\n'
                                             '      dtype=float32)',
                                    'name': 'reproduced test outputs from test '
                                            'inputs',
                                    'traceback': None}}
```
Maybe we should consider going to 2 decimals to be less restrictive here.

**Comment by oeway** [comment]
@constantinpape I got this error now:
```
[{'error': 'Output and expected output disagree:\n'
           ' \n'
           'Arrays are not almost equal to 4 decimals\n'
           '\n'
           'Mismatched elements: 159 / 2048 (7.76%)\n'
           'Max absolute difference: 0.00132132\n'
           'Max relative difference: 0.08016495\n'
           ' x: array([[0.0214, 0.3054, 0.0507, ..., 0.4618, 0.0332, '
           '0.0118]],\n'
           '      dtype=float32)\n'
           ' y: array([[0.0214, 0.3055, 0.0507, ..., 0.4618, 0.0332, '
           '0.0118]],\n'
           '      dtype=float32)',
  'id': 'validation_summary_onnx',
  'name': 'reproduced test outputs from test inputs',
  'traceback': None},
 {'error': 'Output and expected output disagree:\n'
           ' \n'
           'Arrays are not almost equal to 4 decimals\n'
           '\n'
           'Mismatched elements: 159 / 2048 (7.76%)\n'
           'Max absolute difference: 0.00132108\n'
           'Max relative difference: 0.08019311\n'
           ' x: array([[0.0214, 0.3054, 0.0507, ..., 0.4618, 0.0332, '
           '0.0118]],\n'
           '      dtype=float32)\n'
           ' y: array([[0.0214, 0.3055, 0.0507, ..., 0.4618, 0.0332, '
           '0.0118]],\n'
           '      dtype=float32)',
  'id': 'validation_summary_torchscript',
  'name': 'reproduced test outputs from test inputs',
  'traceback': None}]
```

Right now, it seems there is some issue with the test output file I provided.

Nevertheless, I am now thinking that maybe we should allow configure tolerance in the weight definition.  E.g. for each weight, we can optionally set `atol` and `rtol` as done in numpy: https://numpy.org/doc/stable/reference/generated/numpy.isclose.html

**Comment by constantinpape** [comment]
@oeway I agree that we can be more tolerant with the tests here. Note that we are using `np.testing.assert_array_almost_equal` (https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/resource_tests.py#L141), where this can be achieved by passing `decimals`.

**Comment by FynnBe** [comment]
closing to refresh (due to main ci update)

**Pull request closed without merging**
