### PR TITLE
Update Mitochondria segmentation - TEM - 2D U-Net - ZeroCostDL4Mic

### PR DESCRIPTION
**Pull request by bioimageiobot**
resource id: 10.5281/zenodo.5817052
new versions:
  - 10.5281/zenodo.5850574

sources of new versions:
  - https://zenodo.org/api/files/5ff5e52c-a708-4c93-98c2-160c29204800/rdf.yaml

deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5817052)
maintainers: none specified

### CODE REVIEW

**Comment by oeway** [comment]
Hey @constantinpape and @esgomezm 

This PR comes back again, let's see how the CI goes.

**Comment by oeway** [comment]
@constantinpape The CI still fails `ERROR: No matching distribution found for tensorflow==1.15`, no idea why.

**Comment by constantinpape** [comment]
> @constantinpape The CI still fails `ERROR: No matching distribution found for tensorflow==1.15`, no idea why.

Ok, I will see if I can figure out where the pip import is coming from. We may need to ask for a range hard pinning may not work for these tf versions.

**Comment by oeway** [comment]
It can also be that pip itself is not updated in the conda env, we may need to upgrade pip first.

**Comment by constantinpape** [comment]
I have fixed the tensorflow installation here. Now the keras validation fails. This is somewhat expected, as we just install some random keras (or maybe just use keras from inside tensorflow). And we have seen that it's difficult to make this one passed.
That's why we decided to not validated keras models a while back, because it's impossible to set up a single consistent environment with keras and tf for these models. However we don't have this constraint anymore because we can use separate envs now. But for this we need to specify the keras dep via conda or pip in the model. (And for proper dependency handling the dependency should be moved as an optional field into the weight formats, so that different weights can have different dependencies: we need to do another model spec update with this).

**Pull request merged**
