### PR TITLE
Update HPA Cell Segmentation (DPNUnet)

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6200635.
The following version(s) will be added:
  - 10.5281/zenodo.6200636

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/a24a1e8a-cdc5-4b56-b9c3-0b82417e74a5/rdf.yaml

The corresponding deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.6200635)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Edit the current resource.yaml and mark the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Merge this PR for now, wait until the CI on the main branch to complete. It should detect the new versions and create another PR for the new version. You can take it from there instead.

### CODE REVIEW

**Comment by oeway** [comment]
@constantinpape Could you look into the failing validation? Should we upgrade the core library or something? I took the files you sent me and it should work, right?

**Comment by FynnBe** [comment]
> @constantinpape Could you look into the failing validation? Should we upgrade the core library or something? I took the files you sent me and it should work, right?

looks like the error in https://github.com/bioimage-io/core-bioimage-io-python/issues/225 which is fixed in https://github.com/bioimage-io/core-bioimage-io-python/pull/226. These changes have note yet been released. 
Ideally we merge https://github.com/bioimage-io/spec-bioimage-io/pull/396 and https://github.com/bioimage-io/core-bioimage-io-python/pull/227 which would be nice to have released quickly...

**Comment by constantinpape** [comment]
> looks like the error in [bioimage-io/core-bioimage-io-python#225](https://github.com/bioimage-io/core-bioimage-io-python/issues/225) which is fixed in [bioimage-io/core-bioimage-io-python#226](https://github.com/bioimage-io/core-bioimage-io-python/pull/226). These changes have note yet been released.

Yes, indeed.

> Ideally we merge [bioimage-io/spec-bioimage-io#396](https://github.com/bioimage-io/spec-bioimage-io/pull/396) and [bioimage-io/core-bioimage-io-python#227](https://github.com/bioimage-io/core-bioimage-io-python/pull/227) which would be nice to have released quickly...

Sounds good. I had a quick look at this and merging it is fine with me, feel free to go ahead with this.

**Comment by oeway** [comment]
@FynnBe Could you also trigger the main CI under your forked collection repo so I can also test it?

**Pull request closed without merging**
