### PR TITLE
Update 3D UNet - arabidopsis - ZeroCostDL4Mic

### PR DESCRIPTION
**Pull request by bioimageiobot**
resource id: 10.5281/zenodo.5749843
new versions:
  - 10.5281/zenodo.5749844

sources of new versions:
  - https://zenodo.org/api/files/3320859e-af1a-45bc-bfaa-3d4110b3bc41/rdf.yaml

deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5749843)
maintainers: none specified

IMPORTANT: If new resource versions are detected this PR branch is beeing **force-pushed**.
Either merge any manual changes before updates to the external resource occur
or keep your updates safe in a separate branch and make a PR on [this PR's branch](/bioimage-io/collection-bioimage-io/tree/auto-update-10.5281/zenodo.5749843).

### CODE REVIEW

**Comment by FynnBe** [comment]
comitted 1e58894 to check if @bioimageiobot force-pushes it away...

**Comment by FynnBe** [comment]
the problem with the dynamic validation here is that the specified tensorflow version (1.15.2) cannot be found. (attempting to install like pip like tensorflow website recommends, fails with conda as well (not in this CI run))

**Comment by constantinpape** [comment]
@esgomezm could you check what the issue with the tensorflow version is here

**Comment by esgomezm** [comment]
Hi! 

This is weird because the TF version is actually 1.15.2:

```
%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)

> TensorFlow 1.x selected.
> 1.15.2
```

**Comment by constantinpape** [comment]
> Hi!
> 
> This is weird because the TF version is actually 1.15.2:

I think the problem is that you specify the patch version. Could you change it to just 1.15?

**Comment by constantinpape** [comment]
On second thought: can we fix this in the code, so that we ignore the patch version of in tf_version?
I think that could avoid a lot of errors downstream.

**Pull request closed without merging**
