### PR TITLE
Update 3D UNet - arabidopsis - ZeroCostDL4Mic

### PR DESCRIPTION
**Pull request by bioimageiobot**
resource id: 10.5281/zenodo.5749843
new versions:
  - 10.5281/zenodo.5749844

sources of new versions:
  - https://zenodo.org/api/files/3320859e-af1a-45bc-bfaa-3d4110b3bc41/rdf.yaml

deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5749843)
maintainers: none specified

### CODE REVIEW

**Comment by constantinpape** [comment]
The validation now fails because there is an issue with how the tensorflow weights are zipped: in the model here the zip contains an extra folder `tensorflow_saved_model_bundle` that contains `saved_model.pb` etc. However `saved_model.pb` and the rest need to be at the root of the zip archive. See
image

@esgomezm I have checked and I am sure that this issue does not occur when you are using `bioimageio.core` functionality to create the model (at least not if you are using the most recent version). So it seems like you are still using some of your old code for exporting the model, which causes this issue. Could you please double check.

**Comment by esgomezm** [comment]
Hey! This model has not been generated by the bioimageio.core. It's "an old" model but I cannot change it as it was uploaded by @crtorreg

**Comment by constantinpape** [comment]
Thanks for checking this out @esgomezm. Do you think you could update the 3d unet notebook so that it also uses the bioimageio.core functionality and then update this model instead?

**Comment by crtorreg** [comment]
Hi, I have just updated the model! Let me know if anything else is needed or something is wrong.

**Comment by oeway** [comment]
> Hi, I have just updated the model! Let me know if anything else is needed or something is wrong.

It seems the tests are failing because saved model not found, see here: https://github.com/bioimage-io/collection-bioimage-io/runs/4852324795?check_suite_focus=true#step:5:4

**Comment by constantinpape** [comment]
I think that the issue is that we don't update the DOI: the validation still runs for `10.5281/zenodo.5749844` (Version 1), where the issue with the tf weights is present. It should run for `10.5281/zenodo.5888237` (Version 3) though, where the tf weight issue is fixed.

@FynnBe @oeway I think we need to change the edit functionality on the website so that it updates the pending PR so that it uses the DOI of the new version. (Or makes a new PR, whatever is easier to implement.)

As a side-note: when I try to validate `10.5281/zenodo.5888237` I get the following error:
```
Traceback (most recent call last):
  File "debug_model.py", line 46, in <module>
    main()
  File "debug_model.py", line 41, in main
    model_path = download_model(args.input)
  File "debug_model.py", line 13, in download_model
    bioimageio.core.export_resource_package(doi, output_path=out_path)
  File "/home/pape/Work/bioimageio/core-bioimage-io-python/bioimageio/core/resource_io/io_.py", line 113, in export_resource_package
    raw_rd = load_raw_resource_description(source, update_to_format=update_to_format)
  File "/home/pape/software/conda/miniconda3/envs/bio-core-tf/lib/python3.7/site-packages/bioimageio/spec/io_.py", line 193, in load_raw_resource_description
    raw_rd = schema.load(data)
  File "/home/pape/software/conda/miniconda3/envs/bio-core-tf/lib/python3.7/site-packages/marshmallow/schema.py", line 720, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/home/pape/software/conda/miniconda3/envs/bio-core-tf/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'rdf_source': ['Unknown field.']}
```

**Comment by oeway** [comment]
The way it works for now is that we create one PR for each version, if you
don’t want this version, you can change the version status to blocked (keep
the item status to accepted), then close this PR. A new one will open.

We try not to force push to an existing PR, but we can perhaps make a
scripts to update an existing item in the PR to get new versions.

**Comment by oeway** [comment]
> I don't think we need to force-push; ideally the bot would just add a new commit to the existing PR.

Understand but we can only choose to not touch a PR or force push the with GitHub actions we used right now. And I afraid adding a new commit is not an option because an ongoing PR may contain changes, e.g with custom tags, so commit won't be possible. So I would not touch the PR at all.

We can perhaps use the bot to make a comment to a PR to notify the new version, however, we need to figure out a way to detect duplicated comments when running the bot multiple times.

For now, we should document this behavior better in the PR description.

**Comment by constantinpape** [comment]
> Understand but we can only choose to not touch a PR or force push the with GitHub actions we used right now. And I afraid adding a new commit is not an option because an ongoing PR may contain changes, e.g with custom tags, so commit won't be easily possible. So I would not touch the PR at all.

I see. I agree that if we only have the option between not touching the PR at all and force pushing we should not touch it.

> We can perhaps use the bot to make a comment to a PR to notify the new version, however, we need to figure out a way to detect duplicated comments when running the bot multiple times.
> 
> Or implement a more complex logic to checkout a PR branch and load the current RDF then add a new version to the list.
>

I think both of this would be good once we have time to look into this again.

> For now, I think we should document this behavior better in the PR description.

Yep, we should do this ASAP.

**Comment by constantinpape** [comment]
@oeway I am not sure what exactly I need to change in this PR to bring it to the newest version. Could you please make the change here and then document it in the PR message so that we can update models in the future?
The new version is 10.5281/zenodo.5888237.

**Comment by oeway** [comment]
Close this PR in favor of the next version.

**Comment by FynnBe** [comment]
small note: closing a PR with status "pending" leads to the bot changing the status to "blocked". Thus this commit: 684ef44 is not required.

**Comment by oeway** [comment]
> 

@FynnBe Could you make sure it only change version status, but keep the whole item status accepted? This is required to detect changes for future versions.

**Comment by oeway** [comment]
> small note: closing a PR with status "pending" leads to the bot changing the status to "blocked". Thus this commit: [684ef44](https://github.com/bioimage-io/collection-bioimage-io/commit/684ef44f320c5157a7357ee004a1b6cd7a8a2430) is not required.

@FynnBe  I think maybe we should disable this "feature".  Normally, when closing a PR, it means we want to discard any changes in the current PR and leave the main branch untouched. One won't expect the bot to make a commit to the main branch when we close a PR.

Plus, since we have changed how to detect pending items, the only thing need is actually trigger the main CI again when we close the an auto PR. Because then, there won't be any existing PR created already for the item so it should treat it as pending item, correct?

This means we should disable that auto mark blocked feature, and we actually have two ways of dealing with this case 1) close the PR and trigger the main CI 2) manually mark the version item as blocked, and merge the PR.

**Comment by constantinpape** [comment]
> @FynnBe I think maybe we should disable this "feature". Normally, when closing a PR, it means we want to discard any changes in the current PR and leave the main branch untouched. One won't expect the bot to make a commit to the main branch when we close a PR.
> 
> Plus, since we have changed how to detect pending items, the only thing need is actually trigger the main CI again when we close the an auto PR. Because then, there won't be any existing PR created already for the item so it should treat it as pending item, correct?
> 
> This means we should disable that auto mark blocked feature, and we actually have two ways of dealing with this case 1) close the PR and trigger the main CI 2) manually mark the version item as blocked, and merge the PR.

I agree with @oeway here. Auto-blocking is not a good idea; if we want to block an item it should be done manually. If the PR is closed we can just leave the item pending.

**Comment by FynnBe** [comment]
alright. with how the scripts work now we can do this. If it becomes an issue we can always add a script that can be triggered manually to block pending versions without open PR.
I'll remove the auto-block.

**Comment by oeway** [comment]
> 

Sounds good! Maybe we can trigger the main CI when one close an auto PR instead.

Also it would be helpful if we can make a script for fetching new version for a particular resource item so we can manually update the versions in a PR.

**Comment by FynnBe** [comment]
> Sounds good! Maybe we can trigger the main CI when one close an auto PR instead.

it is triggered on merge, why would you want it to run on close wo merge?

> Also it would be helpful if we can make a script for fetching new version for a particular resource item so we can manually update the versions in a PR.

yeah, why not, although just closing the PR and waiting for the new one to pop up wouldn't be so bad either.. I'm looking into linking those PRs, which might be useful in general.

**Comment by oeway** [comment]
> it is triggered on merge, why would you want it to run on close wo merge?

When we close an auto PR without doing anything, we mostly want to get a new auto PR with the new versions. Without triggering the main CI we won't get it right away.


> yeah, why not, although just closing the PR and waiting for the new one to pop up wouldn't be so bad either.. I'm looking into linking those PRs, which might be useful in general.

No big difference, but sometimes we might want to keep the conversation in the same PR.

**Comment by constantinpape** [comment]
> yeah, why not, although just closing the PR and waiting for the new one to pop up wouldn't be so bad either.. I'm looking into linking those PRs, which might be useful in general.

Linking the PRs would be pretty helpful to keep the context.

**Comment by FynnBe** [comment]
> When we close an auto PR without doing anything, we mostly want to get a new auto PR with the new versions. Without triggering the main CI we won't get it right away.

oh true, of course!

**Comment by FynnBe** [comment]
> When we close an auto PR without doing anything, we mostly want to get a new auto PR with the new versions. Without triggering the main CI we won't get it right away.

implemented in https://github.com/bioimage-io/collection-bioimage-io/pull/261

**Pull request merged**
