### PR TITLE
Add notebook links to torch-em models

### PR DESCRIPTION
**Pull request by constantinpape**

### CODE REVIEW

**Comment by constantinpape** [comment]
Hey @FynnBe,
I am trying to update some models to add links to notebooks. But now the step `update_partner_resources` is failing with the following error:
```
Traceback (most recent call last):
  File "scripts/update_partner_resources.py", line 47, in <module>
    typer.run(main)
  File "/home/runner/.local/lib/python3.8/site-packages/typer/main.py", line 864, in run
    app()
  File "/home/runner/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "scripts/update_partner_resources.py", line 22, in main
    partners, updated_partner_resources, new_partner_hashes, ignored_partners = resolve_partners(
  File "/home/runner/work/collection-bioimage-io/collection-bioimage-io/scripts/utils.py", line 148, in resolve_partners
    resolve_collection_entries(partner_collection, collection_id=partner_id)
  File "/home/runner/.local/lib/python3.8/site-packages/bioimageio/spec/collection/v0_2/utils.py", line 75, in resolve_collection_entries
    rdf_data["links"][i] = collection.id + "/" + link
TypeError: unsupported operand type(s) for +: '_Missing' and 'str'
Error: Process completed with exit code 1.
```
Any idea what's going wrong here?

**Comment by FynnBe** [comment]
Caused recent changes in bioimageio.spec https://github.com/bioimage-io/collection-bioimage-io/pull/399 fixed this already.

**Comment by FynnBe** [comment]
@constantinpape I hope I have not merged this PR prematurely. I just noticed that it removes some dataset links. Checkout the diff here: https://github.com/bioimage-io/collection-bioimage-io/commit/804029d11a4f164c45b82d88280980bbcbeedb4f

**Comment by constantinpape** [comment]
> @constantinpape I hope I have not merged this PR prematurely. I just noticed that it removes some dataset links. Checkout the diff here: [804029d](https://github.com/bioimage-io/collection-bioimage-io/commit/804029d11a4f164c45b82d88280980bbcbeedb4f)

No, all good. The dataset links should actually be removed because they need to be `training_data`. I will do that in a follow up PR.

**Comment by constantinpape** [comment]
Followup is in #402

**Pull request merged**
