### PR TITLE
Update Cells and gland Segmentation (FRUNet)

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.6865412.
The following version(s) will be added:
  - [6919253 (version 8)](https://www.doi.org/10.5281/zenodo.6919253)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: https://github.com/bioimage-io/collection-bioimage-io/pull/472, https://github.com/bioimage-io/collection-bioimage-io/pull/473, https://github.com/bioimage-io/collection-bioimage-io/pull/474

### CODE REVIEW

**Comment by oeway** [comment]
@Zoufu1122 All the tests passes now, I will merge now and you should see it on the website soon!

**Comment by Zoufu1122** [comment]
@oeway Thanks a lot!
When will the models be available for download on the BioImage.IO website?
Now the prompt is：Oops, resource item not found: zenodo:6865413. Possibly because it has not been approved yet.

**Comment by oeway** [comment]
Hi @zoufu1122 it's available at https://bioimage.io/#/?tags=frunet&id=10.5281%2Fzenodo.6865412

**Comment by Zoufu1122** [comment]
@oeway Thanks a lot for your help!
I found it!
I want to upload the network through DeepImageJ, how can I convert it to the corresponding version?

image

image

**Comment by oeway** [comment]
hi @Zoufu1122 Right, so that's because you only provided keras weights, you need to convert it to tensorflow saved bundle zip. 
Maybe @constantinpape or @esgomezm can provide some hint on the weight conversion to work with deepimagej?

I just found this might help: https://github.com/bioimage-io/core-bioimage-io-python/blob/1eb7b86bf01e172ee31b87b1f28c057a3b731d15/bioimageio/core/weight_converter/keras/tensorflow.py

**Comment by Zoufu1122** [comment]
@oeway Thanks for your help, I will try to convert it, can I upload it again in the same way as the keras weights upload?

**Comment by oeway** [comment]
You can add another weight file to the same deposit on zenodo, then add a new weight entry to the rdf.yaml file.

**Comment by Zoufu1122** [comment]
@oeway Sorry to bother you, do you have any information about calling models on BioImage.io on the ZeroCostDL4Mic platform?
I tried to convert tensorflow saved bundle zip from keras, but I only found information about converting to tensorflow1 and I am using tensorflow2.
Thanks a lot!

**Comment by esgomezm** [comment]
Hi @Zoufu1122 
some of the ZeroCostDL4Mic notebooks have already the import/export model from BioImage.io integrated (2D,3D UNet for example). Which notebook do you want to use?

To export the model, you can use https://github.com/bioimage-io/core-bioimage-io-python as follows, for example:

```python
# export the model with keras weihgts into a bioimage.io model.
# fill in the corresponding information about the model
build_model(
    weight_uri=weight_path,
    test_inputs=[test_in_path],
    test_outputs=[test_out_path],
    name=Trained_model_name,
    description=Trained_model_description,
    authors=authors,
    tags=['zerocostdl4mic', 'deepimagej', 'segmentation', 'tem', 'unet'],
    license=license,
    documentation=readme_path,
    cite=citations,
    output_path=output_path,
    add_deepimagej_config=True,
    tensorflow_version=tf.__version__,
    attachments=attachments,
    training_data = training_data,
    **kwargs
)

# convert the keras weights to tensorflow, store it in tf_weight_path,  and add them to the model
# we need to make sure that the tf weight folder does not exist
if os.path.exists(tf_weight_path):
  rmtree(tf_weight_path)
# output_path is the zip corresponding to the bioimage.io model
convert_weights_to_tensorflow_saved_model_bundle(output_path, tf_weight_path + ".zip")
# add the weight description to the model yaml
add_weights(output_path, tf_weight_path + ".zip", output_path, tensorflow_version=tf.__version__)
```

**Comment by Zoufu1122** [comment]
Hi @esgomezm 
I wonder if it's possible to integrate the network I uploaded to Bioimage.io into ZeroCostDL4Mic notebooks？

Because I use the tensorflow2 framework，when export the model, convert_weights_to_tensorflow_saved_model_bundle has the message:
"Weight conversion for tensorflow 2 is not yet implemented."

**Comment by esgomezm** [comment]
Hi @Zoufu1122 

Is this the model you are referring to? [impartial-shark
](https://bioimage.io/#/?tags=Cells%20and%20gland%20Segmentation&id=10.5281%2Fzenodo.6865412)

What we do in ZCDL4M is to consume some of the trained models that are in the zoo and that were previously trained with ZCDL4M, as otherwise, they are not really compatible. Note that ZCDL4M provides notebooks (i.e., code) to train, test and infer. This means that if your model has been trained with a different notebook ([FRUNet one](https://bioimage.io/#/?type=application&tags=frunet&id=deepimagej%2Fevstemsegmentationfrunet)?), it cannot be consumed in ZCDL4M. 

In deepImageJ at the moment we cannot consume models from TF 2. Some TF 2 versions (2.1, 2.2, 2.3) are still backwards compatible. You can try loading the network using this versions and then, export the model (without compilation) into tensorflow bundled model. 

If there's anything unclear, please, do not hesitate asking about it.

**Pull request merged**
