### PR TITLE
Add BiaPy as a community partner

### PR DESCRIPTION
**Pull request by danifranco**
Hi BMZ team!

We would like to join as a community partner with [BiaPy](https://github.com/danifranco/BiaPy), an open source Python library for building bioimage analysis pipelines. This repository is actively under development by the Biomedical Computer Vision group at the [University of the Basque Country](https://www.ehu.eus/en/en-home) and the [Donostia International Physics Center](http://dipc.ehu.es/). The library provides an easy way to create image processing pipelines that are typically used in the analysis of biology microscopy images in 2D and 3D. Namely, BiaPy contains ready-to-use solutions for the tasks of [semantic segmentation](https://biapy.readthedocs.io/en/latest/workflows/semantic_segmentation.html), [instance segmentation](https://biapy.readthedocs.io/en/latest/workflows/instance_segmentation.html), [object detection](https://biapy.readthedocs.io/en/latest/workflows/detection.html), [image denoising](https://biapy.readthedocs.io/en/latest/workflows/denoising.html), [single image super-resolution](https://biapy.readthedocs.io/en/latest/workflows/super_resolution.html), [self-supervised learning](https://biapy.readthedocs.io/en/latest/workflows/self_supervision.html) and [image classification](https://biapy.readthedocs.io/en/latest/workflows/classification.html). The source code is based on Pytorch as backend.

Do not hesitate to contact me if there is some problem or if we missed something to become a community partner. We will set up the continuous integration (as described in [your doc](https://bioimage.io/docs/#/community_partners/how_to_join?id=how-to-setup-ci-service-for-a-community-partners39-repo) as soon as possible).

Thank you so much for your time!

### CODE REVIEW

**Comment by FynnBe** [comment]
Great to see how you're almost ready to join!
One minor ting I noticed was the capital `id`s (with the additional `_biapy` ending). I propose minor changes in https://github.com/danifranco/BiaPy-bioimage-io/pull/1

I also propose to add a validation workflow: https://github.com/danifranco/BiaPy-bioimage-io/pull/2
Once that one passes the CI here should also pass and you'd be all set as a community partner from my side.

**Comment by danifranco** [comment]
Thank you for the changes made @FynnBe ! Just noticed that one of the checks failed. Do I need to do something else from my side?

**Comment by oeway** [comment]
@danifranco As one of the condition for the bioimage.io community partner:
> To make the maintainance easier, we also ask you to add one of the admin member as collabrators in your resource collection repository. This will make it easier for us to help you maintaining your collection, and keep synchronized in case we make changes to the specification.

Could you please add me (@oeway) to the collaborator?

**Comment by danifranco** [comment]
Sure!! I just added you as a collaborator!

**Pull request merged**
