### PR TITLE
Update Boundary segmentation

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.7380171.
The following version(s) will be added:
  - [7380172 (version 1)](https://www.doi.org/10.5281/zenodo.7380172)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by FynnBe** [comment]
Some points to improve:
-  [ ] because of `keras_hdf5 weights are currently not validated` it would be great to add tensorflow_saved_model_bundle weights to this model as well to have some dynamic validation.
- [ ] I'd suggest to change the name to something less generic.
- [ ] the citation doi `doi:10.1002/xyzacab123` is not valid

**Comment by esgomezm** [comment]
Hey @FynnBe I'm working on this one with @odinsbane we'll work on getting the points you highlighted

**Comment by odinsbane** [comment]
I updated my build script to point at the tensorflow bundle, built and verified the model. So I have the values for the weights.

> tensorflow_saved_model_bundle: {sha256: ae5d5287b90d4b5406f2b6de8e40f50faaf7336d38a2a91d9a66364897a82bed,
    source: drosophila-crb-d5.zip, tensorflow_version: '2.5'}

I updated the name, 

> name: ' Drosophila epithelia cell boundary segmentation of 2D projections'

So I suppose the next step is to update the zenodo repo by editing the rdf.yaml file and uploading the weights bundle?

**Comment by FynnBe** [comment]
> So I suppose the next step is to update the zenodo repo by editing the rdf.yaml file and uploading the weights bundle?

yes, please edit the existing zenodo record (to create version 2) and do not create another record.

I will now block this current version, so a new PR will be created for version 2.

**Comment by odinsbane** [comment]
Okay, I have created a new .zip file. and this is the rdf.yaml.

```
authors:
- {name: 'Smith, MB'}
- {name: 'Herszterg, S'}
- {name: 'Salbreux, S'}
- {name: 'Vincent, JP'}
covers: [cover.png]
description: For segmenting 2D projections of drosophila epithelia
documentation: epithelia.md
format_version: 0.4.8
inputs:
- axes: bczyx
  data_range: [0.0, 255.0]
  data_type: uint8
  name: input0
  shape: [1, 1, 3, 64, 64]
license: CC-BY-4.0
name: ' Drosophila epithelia cell boundary segmentation of 2D projections'
outputs:
- axes: bczyx
  data_range: [-.inf, .inf]
  data_type: float32
  name: output0
  shape: [1, 1, 3, 64, 64]
- axes: bczyx
  data_range: [-.inf, .inf]
  data_type: float32
  name: output1
  shape: [1, 2, 3, 64, 64]
- axes: bczyx
  data_range: [-.inf, .inf]
  data_type: float32
  name: output2
  shape: [1, 2, 3, 64, 64]
tags: [drosophila, fluorescence-light-microscopy, 2d, unet, cells, image-classification,
  tensorflow]
test_inputs: [sample.npy]
test_outputs: [distance.npy, membrane-we.npy, membrane-dl.npy]
timestamp: '2022-11-30T15:04:50.591037'
type: model
weights:
  tensorflow_saved_model_bundle: {sha256: ae5d5287b90d4b5406f2b6de8e40f50faaf7336d38a2a91d9a66364897a82bed,
    source: drosophila-crb-d5.zip, tensorflow_version: '2.5'}
```
I think this rdf file addresses the issues from our email?

- Extending the model description (e.g., what architecture you use, whether the data is publicly available or will be published with the paper, is it live microscopy? all this information that can be nice for other users and also to have a well documented model). 
- Adding the names of the authors of the paper. As you do not have any published paper yet, this is a way to give proper credits. 
- As there is no paper yet, I would not include anything in the references. Once your paper/preprint is published, you can update this information in the model. 


So now I need to update the zenodo repo by replacing the rdf.yaml, uploading the tensorflow bundle, and deleting the .h5 file?

Thank you!

**Comment by esgomezm** [comment]
Hey!

> * Extending the model description (e.g., what architecture you use, whether the data is publicly available or will be published with the paper, is it live microscopy? all this information that can be nice for other users and also to have a well documented model).

Could you please provide a more extended description? Or is it included in `documentation: epithelia.md`?

> * Adding the names of the authors of the paper. As you do not have any published paper yet, this is a way to give proper credits.

Perfect! If you want you can also add some institutional information:
````
authors:
- {name: 'Smith, MB', affiliation: "XXXX"}
- {name: 'Herszterg, S', affiliation: "XXXX"}
- {name: 'Salbreux, S', affiliation: "XXXX"}
- {name: 'Vincent, JP', affiliation: "XXXX"}
````

> So now I need to update the zenodo repo by replacing the rdf.yaml, uploading the tensorflow bundle, and deleting the .h5 file?

No, you don't delete the .h5 model. Just keep both formats! This way your model can be used in deepImageJ as well for example. 
 
> Thank you!

Thank  YOU!

**Comment by odinsbane** [comment]
I tried publishing a new version. I've improved the metadata and included both versions of the model. I associated it to the bioimage.io community so now I just wait?

Cheers

**Comment by FynnBe** [comment]
> so now I just wait?

yes, @oeway  please approve the zenodo record for the BioImage.IO zenodo community 👋

**Pull request merged**
