### PR TITLE
Update 3D U-Net - ZeroCostDL4Mic

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.5940478.
The following version(s) will be added:
  - 10.5281/zenodo.5940479

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/92c3196a-02c6-4ebe-8b5c-326737e9d9d0/rdf.yaml

The corresponding deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5940478)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @esgomezm, @crtorreg

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Edit the current resource.yaml and mark the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Merge this PR for now, wait until the CI on the main branch to complete. It should detect the new versions and create another PR for the new version. You can take it from there instead.

### CODE REVIEW

**Comment by constantinpape** [comment]
This model fails with:
```
{'error': 'Cannot load '
                                                               'file '
                                                               'containing '
                                                               'pickled data '
                                                               'when '
                                                               'allow_pickle=False',
                                                      'name': 'reproduced test '
                                                              'outputs from '
                                                              'test inputs',
```
I am not sure why. Also, what exactly is this model and how is it different from the one we already have on the website (https://bioimage.io/#/?id=10.5281%2Fzenodo.5749843)? cc @esgomezm @crtorreg

**Comment by FynnBe** [comment]
weirdly it looks like the test input/output files do not exist? Which might also explain the error if instead of the .npy file we download some 404 response. 
I've seen the same error message when trying to load a .tiff file with numpy.load...

The zenodo record is definitely missing files. It only contains a model.yaml and the rdf.yaml file: https://doi.org/10.5281/zenodo.5940478

**Comment by oeway** [comment]
> weirdly it looks like the test input/output files do not exist? Which might also explain the error if instead of the .npy file we download some 404 response. I've seen the same error message when trying to load a .tiff file with numpy.load...
> 
> The zenodo record is definitely missing files. It only contains a model.yaml and the rdf.yaml file: https://doi.org/10.5281/zenodo.5940478

Ok, so that's why, the message can be a bit more clear then, maybe print something like "file not found".

**Comment by FynnBe** [comment]
closing to refresh (due to main ci update)

**Pull request closed without merging**
