### PR TITLE
Insert test summaries into deployed RDF

### PR DESCRIPTION
**Pull request by FynnBe**
This PR also ensures we always work with the deployed (potentially updated through this collection repo) RDF from gh-pages.
The test summaries are then added to the deployed RDF

### CODE REVIEW

**Comment by FynnBe** [comment]
once we are happy with the changes we should reset gh-pages once to clean up the generated RDFs

**Comment by FynnBe** [comment]
the script 'run_local.py' is now a bit more helpful and generated artifacts into an 'artifacts' folder and also runs the update_known_resources and generate_collection_rdf scripts

**Comment by oeway** [comment]
Looks good, please go ahead and merge it.

BTW, will you also remove the environment files for each item folder in gh-pages, they seems not useful, or maybe can be absorbed into the test summary, what do you think?

**Review by oeway — APPROVED** [review]

**Comment by FynnBe** [comment]
I'm thinking we should drop them. If we do safe anything to the test summaries, maybe a pinned version of it with the dependencies that were actually installed in the test env... but let's put that off for later. I'll remove the files for now...

**Comment by oeway** [comment]
@FynnBe Could you trigger a regeneration of the items in gh-pages so I can check if I can display the test_summary on the website later? Should we just remote all files in the generated collection folder?

**Comment by FynnBe** [comment]
there were some small issues, but with https://github.com/bioimage-io/collection-bioimage-io/pull/263 it should now generate the `test_summary` into the existing rdf.yamls.. 
let's reset gh-pages once we are happy with how it works

**Comment by FynnBe** [comment]
.. and when it works ;-)

**Pull request merged**
