### PR TITLE
Better name, tags and description

### PR DESCRIPTION
**Pull request by akreshuk**

### CODE REVIEW

**Comment by oeway** [comment]
@akreshuk Thanks! Looks good!

@FynnBe For regular PR, can we run the CI to generate the final collection and the summary? (It seems we are not running it as I understand) Otherwise, we don't know whether it will work, e.g. if we have a syntax error in the yaml file, right?

**Comment by oeway** [comment]
@akreshuk can we make the name shorter, you know if the name is too long, we will show the extra part as `...`. Would  it make sense to change `Cell Segmentation from Membrane Staining for Plant Tissues` to `Plant Tissue Cell Membrane Segmentation`?

**Comment by constantinpape** [comment]
@FynnBe do you know why the dynamic tests fail here?

**Comment by FynnBe** [comment]
merging this now and fixing issues with accepted resources separately...

**Pull request merged**
