### PR TITLE
Update 3D UNet Arabidopsis Ovules Nuclei

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.7772662.
The following version(s) will be added:
  - [7772663 (version 1)](https://www.doi.org/10.5281/zenodo.7772663)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @wolny

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by FynnBe** [comment]
<details>
<summary>
error log'Error(s) in loading state_dict for UNet2D'
</summary>

{'bioimageio_core_version': '0.5.8',
   'bioimageio_spec_version': '0.4.9',
   'error': 'Error(s) in loading state_dict for UNet2D:\n'
            '\tsize mismatch for encoders.0.basic_module.SingleConv1.conv.weight: copying a param with shape '
            'torch.Size([16, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 1, 1, 3, '
            '3]).\n'
            '\tsize mismatch for encoders.0.basic_module.SingleConv2.groupnorm.weight: copying a param with shape '
            'torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).\n'
            '\tsize mismatch for encoders.0.basic_module.SingleConv2.groupnorm.bias: copying a param with shape '
            'torch.Size([16]) from checkpoint, the shape in current model is torch.Size([32]).\n'
            '\tsize mismatch for encoders.0.basic_module.SingleConv2.conv.weight: copying a param with shape '
            'torch.Size([32, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 32, 1, 3, '
            '3]).\n'
            '\tsize mismatch for encoders.1.basic_module.SingleConv1.groupnorm.weight: copying a param with shape '
            'torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).\n'
            '\tsize mismatch for encoders.1.basic_module.SingleConv1.groupnorm.bias: copying a param with shape '
            'torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).\n'
            '\tsize mismatch for encoders.1.basic_module.SingleConv1.conv.weight: copying a param with shape '
            'torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 3, '
            '3]).\n'
            '\tsize mismatch for encoders.1.basic_module.SingleConv2.groupnorm.weight: copying a param with shape '
            'torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).\n'
            '\tsize mismatch for encoders.1.basic_module.SingleConv2.groupnorm.bias: copying a param with shape '
            'torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).\n'
            '\tsize mismatch for encoders.1.basic_module.SingleConv2.conv.weight: copying a param with shape '
            'torch.Size([64, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 1, 3, '
            '3]).\n'
            '\tsize mismatch for encoders.2.basic_module.SingleConv1.groupnorm.weight: copying a param with shape '
            'torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).\n'
            '\tsize mismatch for encoders.2.basic_module.SingleConv1.groupnorm.bias: copying a param with shape '
            'torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).\n'
            '\tsize mismatch for encoders.2.basic_module.SingleConv1.conv.weight: copying a param with shape '
            'torch.Size([64, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 1, 3, '
            '3]).\n'
            '\tsize mismatch for encoders.2.basic_module.SingleConv2.groupnorm.weight: copying a param with shape '
            'torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).\n'
            '\tsize mismatch for encoders.2.basic_module.SingleConv2.groupnorm.bias: copying a param with shape '
            'torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).\n'
            '\tsize mismatch for encoders.2.basic_module.SingleConv2.conv.weight: copying a param with shape '
            'torch.Size([128, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 1, 3, '
            '3]).\n'
            '\tsize mismatch for encoders.3.basic_module.SingleConv1.groupnorm.weight: copying a param with shape '
            'torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).\n'
            '\tsize mismatch for encoders.3.basic_module.SingleConv1.groupnorm.bias: copying a param with shape '
            'torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).\n'
            '\tsize mismatch for encoders.3.basic_module.SingleConv1.conv.weight: copying a param with shape '
            'torch.Size([128, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 1, '
            '3, 3]).\n'
            '\tsize mismatch for encoders.3.basic_module.SingleConv2.groupnorm.weight: copying a param with shape '
            'torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).\n'
            '\tsize mismatch for encoders.3.basic_module.SingleConv2.groupnorm.bias: copying a param with shape '
            'torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).\n'
            '\tsize mismatch for encoders.3.basic_module.SingleConv2.conv.weight: copying a param with shape '
            'torch.Size([256, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 256, 1, '
            '3, 3]).\n'
            '\tsize mismatch for decoders.0.basic_module.SingleConv1.groupnorm.weight: copying a param with shape '
            'torch.Size([384]) from checkpoint, the shape in current model is torch.Size([768]).\n'
            '\tsize mismatch for decoders.0.basic_module.SingleConv1.groupnorm.bias: copying a param with shape '
            'torch.Size([384]) from checkpoint, the shape in current model is torch.Size([768]).\n'
            '\tsize mismatch for decoders.0.basic_module.SingleConv1.conv.weight: copying a param with shape '
            'torch.Size([128, 384, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 768, 1, '
            '3, 3]).\n'
            '\tsize mismatch for decoders.0.basic_module.SingleConv2.groupnorm.weight: copying a param with shape '
            'torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).\n'
            '\tsize mismatch for decoders.0.basic_module.SingleConv2.groupnorm.bias: copying a param with shape '
            'torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).\n'
            '\tsize mismatch for decoders.0.basic_module.SingleConv2.conv.weight: copying a param with shape '
            'torch.Size([128, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 1, '
            '3, 3]).\n'
            '\tsize mismatch for decoders.1.basic_module.SingleConv1.groupnorm.weight: copying a param with shape '
            'torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).\n'
            '\tsize mismatch for decoders.1.basic_module.SingleConv1.groupnorm.bias: copying a param with shape '
            'torch.Size([192]) from checkpoint, the shape in current model is torch.Size([384]).\n'
            '\tsize mismatch for decoders.1.basic_module.SingleConv1.conv.weight: copying a param with shape '
            'torch.Size([64, 192, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 384, 1, 3, '
            '3]).\n'
            '\tsize mismatch for decoders.1.basic_module.SingleConv2.groupnorm.weight: copying a param with shape '
            'torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).\n'
            '\tsize mismatch for decoders.1.basic_module.SingleConv2.groupnorm.bias: copying a param with shape '
            'torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).\n'
            '\tsize mismatch for decoders.1.basic_module.SingleConv2.conv.weight: copying a param with shape '
            'torch.Size([64, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 1, 3, '
            '3]).\n'
            '\tsize mismatch for decoders.2.basic_module.SingleConv1.groupnorm.weight: copying a param with shape '
            'torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).\n'
            '\tsize mismatch for decoders.2.basic_module.SingleConv1.groupnorm.bias: copying a param with shape '
            'torch.Size([96]) from checkpoint, the shape in current model is torch.Size([192]).\n'
            '\tsize mismatch for decoders.2.basic_module.SingleConv1.conv.weight: copying a param with shape '
            'torch.Size([32, 96, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 192, 1, 3, '
            '3]).\n'
            '\tsize mismatch for decoders.2.basic_module.SingleConv2.groupnorm.weight: copying a param with shape '
            'torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).\n'
            '\tsize mismatch for decoders.2.basic_module.SingleConv2.groupnorm.bias: copying a param with shape '
            'torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).\n'
            '\tsize mismatch for decoders.2.basic_module.SingleConv2.conv.weight: copying a param with shape '
            'torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 3, '
            '3]).\n'
            '\tsize mismatch for final_conv.weight: copying a param with shape torch.Size([1, 32, 1, 1, 1]) from '
            'checkpoint, the shape in current model is torch.Size([1, 64, 1, 1, 1]).',
   'id': 'validation_summary_pytorch_state_dict',
   'name': 'reproduce test outputs from test inputs',
   'source_name': '10.5281/zenodo.7772662/7772663',
   'status': 'failed',
   'traceback': ['  File '
                 '"/home/runner/micromamba-root/envs/7772663/lib/python3.9/site-packages/bioimageio/core/resource_tests.py", '
                 'line 156, in _test_model_inference\n'
                 '    with create_prediction_pipeline(\n',
                 '  File '
                 '"/home/runner/micromamba-root/envs/7772663/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py", '
                 'line 122, in __enter__\n'
                 '    self.load()\n',
                 '  File '
                 '"/home/runner/micromamba-root/envs/7772663/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py", '
                 'line 180, in load\n'
                 '    self._model.load()\n',
                 '  File '
                 '"/home/runner/micromamba-root/envs/7772663/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py", '
                 'line 57, in load\n'
                 '    self._load(devices=devices or self.default_devices)\n',
                 '  File '
                 '"/home/runner/micromamba-root/envs/7772663/lib/python3.9/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_pytorch_model_adapter.py", '
                 'line 31, in _load\n'
                 '    self._model.load_state_dict(state)\n',
                 '  File '
                 '"/home/runner/micromamba-root/envs/7772663/lib/python3.9/site-packages/torch/nn/modules/module.py", '
                 'line 1[48](https://github.com/bioimage-io/collection-bioimage-io/actions/runs/4527196081/jobs/7972861050?pr=577#step:9:49)2, in load_state_dict\n'
                 "    raise RuntimeError('Error(s) in loading state_dict for {}:\\n\\t{}'.format(\n"],
   'warnings': {}}]]

</details>

**Comment by wolny** [comment]
I'm pretty sure I've fixed this in the latest version. Why is the bot not picking it up?

**Comment by FynnBe** [comment]
> I'm pretty sure I've fixed this in the latest version. Why is the bot not picking it up?

have you used the bioimage.io uploader or edited the record directly on zenodo?

**Comment by FynnBe** [comment]
I don't have time for this now, but you could try to download from zenodo and test locally with bioimageio.core...  that should give the same error...

**Comment by wolny** [comment]
I've changed the file directly on zenodo before, now it's in version 3 (https://zenodo.org/record/7774321). I though the bot would scan and automatically pick the new version. What's the best way to proceed then, uploading via bioimage.io doesn't make sense now, because the files will be the same?

**Comment by FynnBe** [comment]
> I've changed the file directly on zenodo before, now it's in version 3 (https://zenodo.org/record/7774321). I though the bot would scan and automatically pick the new version. What's the best way to proceed then, uploading via bioimage.io doesn't make sense now, because the files will be the same?

ah, I see. We limit the number of PRs per resource to 1. So I'm going to block this version 1 and then we'll get a new PR with version 2 and 3...

**Pull request merged**
