### PR TITLE
Update B. Sutilist bacteria segmentation - Widefield microscopy - 2D UNet

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.7261974.
The following version(s) will be added:
  - [7688940 (version 3)](https://www.doi.org/10.5281/zenodo.7688940)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @esgomezm

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: https://github.com/bioimage-io/collection-bioimage-io/pull/498, https://github.com/bioimage-io/collection-bioimage-io/pull/520

### CODE REVIEW

**Comment by esgomezm** [comment]
@FynnBe @oeway @constantinpape 
The CI is failing :(

````
Run python scripts/dynamic_validation.py dist/dynamic_validation_artifact 10.5281/zenodo.7261974 7688940 tensorflow_saved_model_bundle --create-env-outcome failure --ignore-rdf-source-field-in-validation
Traceback (most recent call last):
  File "/home/runner/work/collection-bioimage-io/collection-bioimage-io/scripts/dynamic_validation.py", line 6, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
Error: Process completed with exit code 1.
````

**Comment by constantinpape** [comment]
@FynnBe I think this one is for you.

**Comment by FynnBe** [comment]
> The CI is failing :(

The actual error happened during the mamba env creation:
```
Encountered problems while solving:
        - nothing provides __cuda needed by tensorflow-2.11.0-cuda112py310he[87](https://github.com/bioimage-io/collection-bioimage-io/actions/runs/4305228097/jobs/7507459923#step:4:89)a039_0
      
      The environment can't be solved, aborting the operation
``` 
I updated the CI, such that this consequential error will not occur and the script can report the error properly.

**Comment by FynnBe** [comment]
unfortunately the generated conda env file does not seem to be found.. this is unrelated to this resource. I'm fixing it...

**Comment by FynnBe** [comment]
the issue is that tensorflow 2.11 is not available on the conda 'defaults' channel (yet).
Due to conda-forge not listing many of the old tensorflow versions we do install tensorflow from the defaults channel.
To fix this we have several options:
1. I update the CI such that for TF >= 2.11 we use conda-forge only and not the defaults channel (note: I think some old tf versions have been deleted from conda-forge, (some were perhaps never there), leading to the current state of installing from defaults)
2. we add a specific conda environment file as `dependencies` to the tf weights in this model
3. we wait for tf 2.11 to appear on the defaults conda channel

@esgomezm , @constantinpape any objections to option 1?

**Comment by constantinpape** [comment]
@FynnBe let's go with option 1.

**Comment by esgomezm** [comment]
thank you!

**Pull request merged**
