### PR TITLE
Update (Empanada) 2D Instance Mitochondrial Segmentation in EM Images - 2D MitoNet

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.10391887.
The following version(s) will be added:
  - [10396023 (version from 2023-12-16)](https://www.doi.org/10.5281/zenodo.10396023)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the bioimage.io CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the bioimage.io admin team member.

Maintainers: @abhishek-bhardwaj-IN

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: https://github.com/bioimage-io/collection-bioimage-io/pull/696

### CODE REVIEW

**Comment by abhishek-bhardwaj-IN** [comment]
@FynnBe I see this PR is merged, but the empanada model is still not available on bioimage.io website. Can you please help with this?

**Comment by FynnBe** [comment]
hi @abhishek-bhardwaj-IN 
first of all thank you for this contribution to the model zoo and your patience! 
As we are moving to a new backend I have uploaded your model to our new backend directly: https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/patient-owl/staged/1/files/bioimageio.yaml

**Comment by FynnBe** [comment]
the tests run atm [here](https://github.com/bioimage-io/collection/actions/runs/8902897167)

**Comment by FynnBe** [comment]
unfortunately tests don't pass, I'll try to take a look at fixing the model soon. 
In the meantime you can try to make the tests pass yourself using `bioimageio.core==0.6.2`

```python
from bioimageio.core import test_description, save_bioimageio_package_as_folder

local = save_bioimageio_package_as_folder("patient-owl/staged/1", output_path="patient-owl-local")

summary = test_description(local)
summary.display()
```

Also I would highly recommend to avoid the `model` kwarg to `Empanada2DInference`.  Why can these not be set after initialization via `nn_module.load_state_dict()`?

**Comment by abhishek-bhardwaj-IN** [comment]
@FynnBe Thanks for looking into it. 
Right now its not possible to remove `model` from kwarg as that will require major refactoring, but it's on our list for upcoming release. Can we proceed as it is now? Also, I am attaching the empanada-bioimage zip file which passes the above test pipeline.

https://abhibhardwaj-my.sharepoint.com/:u:/g/personal/abhishek_abhibhardwaj_in/Ec05ARkUWv9PuZ2BlZCAE5ABojMixMs2WldiPX-pjWaUbQ?e=vrElpM

**Comment by FynnBe** [comment]
staged again: https://github.com/bioimage-io/collection/actions/runs/8986982672

**Pull request merged**
