### PR TITLE
Update HPA Bestfitting InceptionV3

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.5910854.
The following version(s) will be added:
  - 5911832

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/c8028ef3-de08-459c-b88a-2f0bfd11485b/rdf.yaml

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: #267

### CODE REVIEW

**Comment by constantinpape** [comment]
I checked locally and it works with `decimal=2`. @FynnBe can we make the test less restrictive for this model somehow?

**Comment by FynnBe** [comment]
> I checked locally and it works with `decimal=2`. @FynnBe can we make the test less restrictive for this model somehow?

how about https://github.com/bioimage-io/collection-bioimage-io/pull/343 ?

A general problem this scenario made me think of is that we don't allow to update a field in a field, e.g. `config: bioimageio`. the moment we specify `config` here in the resource.yaml, we overwrite that field. I don't see a good solution here, but we should keep this in mind....

**Comment by constantinpape** [comment]
@FynnBe you probably still need to merge main to make this work

**Comment by FynnBe** [comment]
> @FynnBe you probably still need to merge main to make this work

you are just too fast! 🚀

**Comment by constantinpape** [comment]
```
```

**Comment by FynnBe** [comment]
> Now it looks like the yaml syntax is invalid:

no, I just put the wrong variable name in yaml.load() ...

**Pull request merged**
