### PR TITLE
skip apps validation based on resource type

### PR DESCRIPTION
**Pull request by FynnBe**
as mentioned in https://github.com/bioimage-io/collection-bioimage-io/pull/199#issuecomment-1003978935

### CODE REVIEW

**Comment by oeway** [comment]
Hi, I thought it's better to skip based on file type because notebooks and other RDF based applications has type=application.

**Comment by FynnBe** [comment]
notbooks should have type notebook, but you're right for other RDF based applications. How about we check for both? only apps can be skipped based on file type...

**Comment by oeway** [comment]
Note: There is no notebook type since a while, they are applications with a notebook tag.

**Comment by FynnBe** [comment]
> I think there is also dataset which has its source set to a remote url of the website etc, so I think it's safer to only check the yaml type.

if the resource is directly defined in the partner collection (manifest) source actually holds a dictionary... (unless you changed that?)

**Comment by oeway** [comment]
No I didn't change that, so that should be fine then.

However since the general RDF does not require the source to be a uri  to RDF, it think it's not correct to try to run validation on any source, we should restrict the spec check on yaml file.

**Comment by FynnBe** [comment]
no, that's why source can be a dict for those rdfs directly specified in a partner collection. 
in the static_validation.py script source is always pointing to an RDF or it is a dictionary (which may hold a source key that points anywhere)

**Comment by FynnBe** [comment]
example: https://github.com/bioimage-io/collection-bioimage-io/blob/8b0fbae2fd42ef806742fdf8dedfdb43478b9285/collection/ilastik/mitoem_segmentation_challenge/resource.yaml

and at https://github.com/bioimage-io/collection-bioimage-io/blob/8b0fbae2fd42ef806742fdf8dedfdb43478b9285/collection/ilastik/ilastik/resource.yaml it's probably not updated yet... there should be a dict there under source and not just this link to a non-rdf file...

**Comment by oeway** [comment]
I know that source dict, but we also support add an item with only id and source key which further link to another RDF, or a non-RDF. In the example link above, you see that we a inner source key link to a website. In my previous version, I always resolve the inner source link and run parsing/validation with that. Here maybe we should also resolve the inner source url if it's a yaml file, what do you think?

**Comment by FynnBe** [comment]
I wrote it in such a way that it tries to interpret the source field as RDF source, but doesn't fail if that's not possible. The in-place (in the collection) provided fields are used to update (from an empty dict in failure case) the RDF.
If I understand the current version correctly, we should undo some of your changes to https://github.com/bioimage-io/collection-bioimage-io/blob/fcddc354e8d52172943e133ede6e672e3bddf9c1/scripts/update_known_resources.py#L239-L278

in order to continue with the resource eon that last line (and not "continue" the for loop on failure)

**Comment by oeway** [comment]
Maybe we should have a meeting to really understand what you mean. In the meantime, feel free to change as you like.

**Comment by FynnBe** [comment]
> Maybe we should have a meeting to really understand what you mean. In the meantime, feel free to change as you like.

yes 👍 , let's have that meeting rather sooner than later ;-)

**Comment by FynnBe** [comment]
Disabling opening new auto-update PRs for now to clean up auto-update PRs and branches...

**Pull request merged**
