### PR TITLE
Update Mitochondria segmentation - TEM - 2D U-Net - ZeroCostDL4Mic

### PR DESCRIPTION
**Pull request by bioimageiobot**
resource id: 10.5281/zenodo.5817052
new versions:
  - 10.5281/zenodo.5817053

sources of new versions:
  - https://zenodo.org/api/files/e14f65fa-f480-4503-944a-209e3119b38b/rdf.yaml

deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5817052)
maintainers: none specified

### CODE REVIEW

**Comment by constantinpape** [comment]
> validation fails due to missing pip package `tensorflow==1.15.2`

Where exactly does this explicit pin come from? Just requiring tf 1.15 without specifying the patch version should be fine.

**Comment by oeway** [comment]
@FynnBe BTW, should we change the `source` key in the resource.yaml as well to `rdf_source` to avoid confusion?

**Comment by FynnBe** [comment]
my post-vacation-two-cents:

> > validation fails due to missing pip package `tensorflow==1.15.2`
> 
> Where exactly does this explicit pin come from? Just requiring tf 1.15 without specifying the patch version should be fine.

it comes from this model's rdf: 
```yaml
...
weights:
  keras_hdf5:
    sha256: cdc0cfcc13d01f75a93b25599167bf7cf1572c0c276ea415dccbbe1d143b1489
    source: keras_weights.hdf5
    tensorflow_version: 1.15.2
  tensorflow_saved_model_bundle:
    sha256: 34269e6da7caf38a604bb68f2aaa39662f306064f9a35e7cc81bc42049db87af
    source: tf_weights.zip
    tensorflow_version: 1.15.2
    ```

It should be fixed there, but I suppose the whole model is blocked now, so that resolves it, too...

**Comment by FynnBe** [comment]
> @FynnBe BTW, should we change the `source` key in the resource.yaml as well to `rdf_source` to avoid confusion?

Yes, why not! 👍

**Comment by constantinpape** [comment]
> my post-vacation-two-cents:
> 
> > > validation fails due to missing pip package `tensorflow==1.15.2`
> > 
> > 
> > Where exactly does this explicit pin come from? Just requiring tf 1.15 without specifying the patch version should be fine.
> 
> it comes from this model's rdf:

All of this is outdated a bit and I have changed dependency handling a bit already; here are my thoughts on how we should unify this in the future: https://github.com/bioimage-io/collection-bioimage-io/issues/238

**Pull request merged**
