### PR TITLE
[WIP] Fix PR validation

### PR DESCRIPTION
**Pull request by FynnBe**
after a lot of back and forth, I think I have a good plan to solve the issues with overriding RDFs and treating partner and zenodo resources as equal as reasonable.

```
                   partners                                                     zenodo


gh-pages:     partner_collection/                 rdfs/                      orig_rdfs/
gh-pages:                          ->  (bioimageio collection) rdf.yaml
                         |                         ^^                           |
                         |_________________________||___________________________|
main:                                                     + update from collection/
                                                
                                                                
```

 - partner_collection/ gets updates when the partner collection version is bumped. This directly updates the respective rdfs in rdfs/ as well (push to gh-pages from main ci)
 - for rdfs from zenodo we keep orig_rdfs/ to check every time if the resource in collection/ has changed (i.e. if the updated rdf in rdf/ has changed or is new). updates are being pushed to gh-pages from a main ci
 - in a PR the orig rdf from orig_rdf/ is updated in the PR CI before being validated, nothing needs to be pushed to gh-pages then
 - the final collection rdf is generated from the collection/ and partner_collection/ folder while all known rdfs are present in rdf/ we don't have to iterate and resolve all partners again/check zenodo.

note: I basically renamed the gh-pages folder `resources/` to `rdfs/` as they are by now valid rdfs. In the collection folders the files are still called `resource.yaml` as they are not valid rdf and just keeping resource id linked to the version ids..

### CODE REVIEW

**Review by oeway — COMMENTED** [review]
Hey, the plan sounds good. Would it make sense to merge the orig_rdfs with the partner_collection into `collection`? If you want to differentiate zenodo from other types, we have subfolders named with the partner name (e.g. zero, or 10.5281 for zenodo).

**Comment by FynnBe** [comment]
> Would it make sense to merge the orig_rdfs with the partner_collection into collection?

I don't think so; conceptually they differe a bit.  In orig_rdfs are valid rdf.yaml fiels and only saved not to request them from zenodo over and over again, while partner_collection would hold `resource.yaml` files with resource and version infos. the versions would be directly deployed to rdfs. Partner resources are updated whenever the partner collections has changed (thanks @constantinpape  for this idea, which beats lookig at the partner collection version).

I'll draft this out fully and then we can discuss any caveats or edge cases we find.
All in all this change shouldn't take so long as it's mostly moving code around. no new functionality is needed.

**Comment by oeway** [comment]
> Partner resources are updated whenever the partner collections has changed (thanks @constantinpape for this idea, which beats lookig at the partner collection version).

Oh, so you mean we only re-generate it when we see the collection version changes. But then if the partner repo changes without bump the version, we will have hold a outdated version of the rdf right?

I think we need more explanation discussion on this, I don't see why we need to cache anything for the partner repo, we can basically always pull the latest version and re-generate them every time we run the main CI. And I think we should do the same for zenodo, the reason is that the meta info for a zenodo deposit can get updated without creating a new version.

Correct me if I missed somethign, but I see no disadvantage to pull the rdf over and over again, both for partner and zenodo. In general, caching stuff can go wrong easily and hard to get it right.

I have the feeling that this proposal will require a lot more testing, and if possible, I would try to do a quick fix for the validation error without involving more fundamental changes.

**Comment by constantinpape** [comment]
While the solution described above sounds cleaner than our current set-up, we think that it is better to test this on a dev version of the repo first, see also #269.
(Which also means that for now we want a hotfix ;))

**Comment by FynnBe** [comment]
hotfixing the heck out of it right now... should have something running any moment now... 
I'll dev on https://github.com/FynnBe/collection-bioimage-io afterwards ;-)

**Comment by FynnBe** [comment]
hotfix was successful now:
 - https://github.com/bioimage-io/collection-bioimage-io/pull/267 fails in the validation-passed check after static and dynamic validation ran successfully

**Pull request closed without merging**
