### PR TITLE
Update Pancreatic Phase Contrast Cell Segmentation (U-Net)

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.5914248.
The following version(s) will be added:
  - 10.5281/zenodo.5914249

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/436a4ace-0b71-4bee-bf08-b0c197350a4c/rdf.yaml

The corresponding deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5914248)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @esgomezm, @crtorreg

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Edit the current resource.yaml and mark the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Merge this PR for now, wait until the CI on the main branch to complete. It should detect the new versions and create another PR for the new version. You can take it from there instead.

### CODE REVIEW

**Comment by constantinpape** [comment]
This model fails due to the model check:
```
 {'validation_summary_tensorflow_saved_model_bundle': {'error': 'Output and '
                                                               'expected '
                                                               'output '
                                                               'disagree:\n'
                                                               ' \n'
                                                               'Arrays are not '
                                                               'almost equal '
                                                               'to 4 decimals\n'
                                                               '\n'
                                                               'Mismatched '
                                                               'elements: '
                                                               '16491 / 414720 '
                                                               '(3.98%)\n'
                                                               'Max absolute '
                                                               'difference: '
                                                               '1.\n'
                                                               'Max relative '
                                                               'difference: '
                                                               '1.\n'
                                                               ' x: '
                                                               'array([[[[0.],\n'
                                                               '         '
                                                               '[0.],\n'
                                                               '         '
                                                               '[0.],...\n'
                                                               ' y: '
                                                               'array([[[[0.],\n'
                                                               '         '
                                                               '[0.],\n'
                                                               '         '
                                                               '[0.],...',
                                                      'name': 'reproduced test '
                                                              'outputs from '
                                                              'test inputs',
                                                      'traceback': None}}
```
Does `test-model` work locally for you @esgomezm @crtorreg? If yes, which tensorflow are you using?

**Comment by crtorreg** [comment]
Hi!

Yes, it works locally! The TensorFlow version that we have is the following 1.15.2

**Comment by FynnBe** [comment]
alternative approach to the tf 1.15.2 issue:
we could provide a pip dependency file where tensorflow 1.15.2 is specified (or a conda one with a pip section, the former would be transformed to the latter either way)

**Comment by constantinpape** [comment]
I will look into this.

**Comment by constantinpape** [comment]
@FynnBe can you update this one to see if our changes in the dependencies handling for tf fix the issue?

**Comment by FynnBe** [comment]
so tf 1.15 is not on pip either? or in conflict with something??
```
Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement tensorflow<1.16,>=1.15 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0)
  ERROR: No matching distribution found for tensorflow<1.16,>=1.15
  ```

**Comment by constantinpape** [comment]
> Pip subprocess error:
>   ERROR: Could not find a version that satisfies the requirement tensorflow<1.16,>=1.15 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0)
>   ERROR: No matching distribution found for tensorflow<1.16,>=1.15

This is weird, the following env works for me locally:
```
name: bio-core-tf
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bioimageio.spec
  - conda-build
  - h5py >=2.10,<2.11
  - mypy
  - pip
  - pytest
  - python >=3.7,<3.8  # this environment is only available for python 3.7
  - xarray
  - tifffile
  - keras
  - pip:
    - tensorflow >1.15,<2.0
```
and it installs tf 1.15.5.

**Comment by FynnBe** [comment]
from the static_validation artifact, here is the generated env:
```yaml
channels: [conda-forge, defaults]
dependencies:
- bioimageio.core
- pip
- pip: ['tensorflow >=1.15,<1.16']
name: 10.5281zenodo.5914249

```

**Comment by FynnBe** [comment]
> from the static_validation artifact, here is the generated env: [...]

with that I get a very similar error locally on win:
```
....
Pip subprocess output:

Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement tensorflow<1.16,>=1.15 (from versions: 2.8.0rc1, 2.8.0)
ERROR: No matching distribution found for tensorflow<1.16,>=1.15
```

**Comment by FynnBe** [comment]
> this might be because of the python version: python-3.10.2

yes, py 3.7 seems to be the max for tf 1:
"Python 3.7–3.9
Python 3.9 support requires TensorFlow 2.5 or later.
Python 3.8 support requires TensorFlow 2.2 or later." -- https://www.tensorflow.org/install/pip

I'll add python<3.8 to the env file for the case of tf 1.x ...

**Comment by constantinpape** [comment]
Now it's passing, thanks @FynnBe!

**Pull request merged**
