### PR TITLE
Update Boundary segmentation

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.7380213.
The following version(s) will be added:
  - [7380214 (version 1)](https://www.doi.org/10.5281/zenodo.7380214)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @odinsbane

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by FynnBe** [comment]
@odinsbane, what is this the relation of this version [7380214 (version 1)](https://www.doi.org/10.5281/zenodo.7380214) to [7380172 (version 1)](https://www.doi.org/10.5281/zenodo.7380172) referenced in https://github.com/bioimage-io/collection-bioimage-io/pull/510 ?

**Comment by FynnBe** [comment]
> @odinsbane, what is this the relation of this version [7380214 (version 1)](https://www.doi.org/10.5281/zenodo.7380214) to [7380172 (version 1)](https://www.doi.org/10.5281/zenodo.7380172) referenced in #510 ?

**Comment by FynnBe** [comment]
oops, closed this PR accidentially...

**Comment by FynnBe** [comment]
blocking this completely as duplicate of 10.5281/zenodo.7380171 (https://github.com/bioimage-io/collection-bioimage-io/pull/510)

**Comment by odinsbane** [comment]
I'm not sure how I ended up with different versions. I have one zenodo doi that I know of. https://doi.org/10.5281/zenodo.7380172 I had some issues with zenodo authorization timing out while I was uploading the model bundle. So I uploaded it manually, then used the doi as reference. I'm not sure how so many pr's happened though. I also did enter myself as the maintainer.

**Comment by odinsbane** [comment]
Okay, so I looked at my zenodo upload page. there are 2 entries right now. 1 is the entry bioimage.io created, and I published using with zenodo to get a doi. 2. Was created and published by bioimage.io based on the doi from the first entry.

**Comment by esgomezm** [comment]
Hey there! The doi part is because of the different trials uploading the model. With the other upload you did and for which the pull request is sent we can keep working on one zenodo repo I guess ;)

**Comment by FynnBe** [comment]
> Hey there! The doi part is because of the different trials uploading the model. With the other upload you did and for which the pull request is sent we can keep working on one zenodo repo I guess ;)

yes, 'edit' on zenodo.org definitely works, but also via the bioimage.io uploader there should be this option available:
 
update_deposit

after loading the resource, e.g. via its doi:
image

**Comment by odinsbane** [comment]
I don't really understand this. The upload failed, so I uploaded everything to zenodo, then I tried to upload to bioimage.io using the DOI that zenodo provided. 

I think the best workflow for me in the future would be to create the model using bioimageio.core.build_spec then uploading those results to zenodo, and then associating them to bioimage.io using the published doi.

**Comment by FynnBe** [comment]
> I don't really understand this. The upload failed, so I uploaded everything to zenodo, then I tried to upload to bioimage.io using the DOI that zenodo provided.

For now bioimage.io has no storage space on its own. Uploading through bioimage.io uses your zenodo login to upload to zenodo.org instead. So uploading a record that exists on zenodo to bioimage.io currently does not make sense.

> The upload failed

Could you give some details of what you did and how it failed? Maybe we can improve the BioImage.IO uploader to make it easier and more reliable.


> I think the best workflow for me in the future would be to create the model using bioimageio.core.build_spec then uploading those results to zenodo, [...]

This is possible

> [...] and then associating them to bioimage.io using the published doi.

As mentioned above this part is not required. Instead make sure to link the record to the BioImage.IO community:
image

Once @oeway has approved it our CI will pick up on the record and create a PR such as this one.
When uploading to zenodo.org through the bioimage.io uploader the record is automatically accepted into the BioImage.IO zenodo community, thus the PR is created faster (100% automatic). For this reason we recommend using the BioImage.IO uploader.

**Comment by FynnBe** [comment]
> I follow the process where I upload a zip file. I filled in the information it requested, then validate which went ok, then clicked on upload. During the upload it stopped uploading after 2 files had been uploaded and tells me my zenodo session has expired. Then a pop up window, which if I viewed would stall at a white screen with some text, which sounded like it was still working or should redirect me. Sorry I didn't get the text.

I'm sorry to read that! We have some plans to fundamentally change the upload procedure, but that will take some time to get set up...

> I don't understand this part. Sorry if I am being dense,

worry not, thank you for your great questions! We need to improve this process and its documentation, so having your fresh eyes on this is really helpful! 👍 

> If the upload works, then there will be a record on bioimage.io and a repository on zenodo that are linked together.

not quite that direct: Let me put it into steps:
1. upload a record to zenodo.org
   a) through the bioimage.io uploader using your zenodo credentials. View this as a mere convenience function (when things actually go as intended).
   b) through direct upload to zenodo.org

Now there is a record on zenodo.org.

2. Mark the zenodo record as part of the BioImage.IO Zenodo Community. For details on Zenodo communities see https://zenodo.org/communities/
  a) if uploaded through the bioimage.io uploader we add the 'community mark' automatically
  b) if uploaded manually the BioImage.IO ZENODO Community's curator (currently @oeway ) needs to approve that the zenodo record at hand is allowed to display this link.

Now there is a record on zenodo.org that is marked as being part of the BioImgae.IO Zenodo Community.

3. (automated) The github actions CI of the collection-bioimage-io repository (this repository) scrapes zenodo for records in the BioImage.IO community and creates a PR authored by @bioimageiobot (like this PR).

4. We, the maintainers of the bioimage-io GitHub organization, discuss potential changes with the contributor (you) and by editing the resource.yaml file block/approve the whole record (e.g. [here](https://github.com/bioimage-io/collection-bioimage-io/blob/d425a488fbe317dfbb17894a460325e8df54f7e6/collection/10.5281/zenodo.7380213/resource.yaml#L7)) or the current version of the record (e.g. [here](https://github.com/bioimage-io/collection-bioimage-io/blob/d425a488fbe317dfbb17894a460325e8df54f7e6/collection/10.5281/zenodo.7380213/resource.yaml#L13))

Now, if the 
- resource has been approved: after the CI finished running (triggered by the merge commit of the PR) the record will be displayed on bioimage.io
- resource has been blocked: the record will not show up in bioimage.io and future record versions will be ignored.
- resource version has been blocked (but the resource in general is still approved): if no versions are accepted the record will not be displayed on bioimage.io, but new PRs will be created for future versions of this record.

**Pull request merged**
