### PR TITLE
Update 3D UNet - arabidopsis - ZeroCostDL4Mic

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.5749843.

The following version(s) will be added:
  - 10.5281/zenodo.5888237
  - 10.5281/zenodo.5877226

You can find their corresponding RDF files here:

  - https://zenodo.org/api/files/eb8f4259-001c-4989-b8ea-d2997918599d/rdf.yaml
  - https://zenodo.org/api/files/3759664b-38bf-4ba8-b61d-b017dcf420d1/rdf.yaml

The corresponding deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5749843)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [x] Passed the BioImage.IO Spec validator (static validation)
- [x] Passed the BioImage.IO CI tests (dynamic validations)
- [x] The meta information for the RDF item is complete
  - [x] The tags is complete and describes the model
  - [x] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [x] Authors are provided
  - [x] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [x] Approved by at least one of the BioImage.IO admin team member

Maintainers: @crtorreg, @esgomezm

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Edit the current resource.yaml and mark the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Merge this PR for now, wait until the CI on the main branch to complete. It should detect the new versions and create another PR for the new version. You can take it from there instead.

### CODE REVIEW

**Comment by oeway** [comment]
@constantinpape Here you go.

**Comment by constantinpape** [comment]
Thanks @oeway. 

@crtorreg, @esgomezm I will look into the use-case from the ilastik point of view now and give you an update once I have something.

**Review by constantinpape — APPROVED** [review]

**Comment by esgomezm** [comment]
Hi @constantinpape see if you can use it although note that this model is not the one exported with bioimage.io. It should work in any case though

**Comment by constantinpape** [comment]
> Hi @constantinpape see if you can use it although note that this model is not the one exported with bioimage.io. It should work in any case though

Yes, we are working on making it run with ilastik and everything seems to be working so far. Will let you know if we run into any issues.

**Pull request merged**
