### PR TITLE
Update Drosophila epithelia cell boundary segmentation of 2D projections

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.7380171.
The following version(s) will be added:
  - [7386437 (version 2)](https://www.doi.org/10.5281/zenodo.7386437)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: https://github.com/bioimage-io/collection-bioimage-io/pull/510

### CODE REVIEW

**Comment by esgomezm** [comment]
Hey @odinsbane

The static validation of the rdf.yaml file is not passing. I think it is the weights that are given as a list. Could you please update the yaml file as follows and update the repo? I will merge this branch and weight for the next PR! Applogies for the mess!

```
authors:
- {name: 'Smith, MB'}
- {name: 'Herszterg, S'}
- {name: 'Salbreux, S'}
- {name: 'Vincent, JP'}
covers: [cover.png]
description: For segmenting 2D projections of drosophila epithelia
documentation: epithelia.md
format_version: 0.4.8
inputs:
- axes: bczyx
  data_range: [0.0, 255.0]
  data_type: uint8
  name: input0
  shape: [1, 1, 3, 64, 64]
license: CC-BY-4.0
name: 'Drosophila epithelia cell boundary segmentation of 2D projections'
outputs:
- axes: bczyx
  data_range: [-.inf, .inf]
  data_type: float32
  name: output0
  shape: [1, 1, 3, 64, 64]
- axes: bczyx
  data_range: [-.inf, .inf]
  data_type: float32
  name: output1
  shape: [1, 2, 3, 64, 64]
- axes: bczyx
  data_range: [-.inf, .inf]
  data_type: float32
  name: output2
  shape: [1, 2, 3, 64, 64]
tags: [drosophila, fluorescence-light-microscopy, 2d, unet, cells, image-classification,
  tensorflow]
test_inputs: [sample.npy]
test_outputs: [distance.npy, membrane-we.npy, membrane-dl.npy]
timestamp: '2022-12-01T14:42:37.285816'
type: model
weights:
  tensorflow_saved_model_bundle: {sha256: ae5d5287b90d4b5406f2b6de8e40f50faaf7336d38a2a91d9a66364897a82bed,
    source: drosophila-crb-d5.zip, tensorflow_version: '2.5'}
  keras_hdf5: {sha256: d2a59e737eb8f424b81321ceaaa1b54b0f60cbaf12c3457c9377e2566cddb44b,
    source: cerb-cont-d0-d5-latest.h5, tensorflow_version: '2.5'}
```

**Comment by odinsbane** [comment]
https://zenodo.org/record/7405349

That has the new rdf file and I fixed an author name too.

Cheers
mbs

**Comment by esgomezm** [comment]
OK! I guess it will take some time to open a new PR for this. am I correct @oeway @FynnBe?

**Comment by FynnBe** [comment]
> OK! I guess it will take some time to open a new PR for this. am I correct @oeway @FynnBe?

@oeway needs to accept https://zenodo.org/record/7405349#.Y4-61nbMJjE into the zenodo BioImage.IO community (assuming that it is selected as discussed earlier)... then the PR should be generated within 6 hours

**Pull request merged**
