### PR TITLE
Update HPA Bestfitting InceptionV3

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.5910854.
The following version(s) will be added:
  - 10.5281/zenodo.5910855

You can find their corresponding RDF files here:
  - https://zenodo.org/api/files/474cde37-dc44-46f3-8343-aed6bafdd0bb/rdf.yaml

The corresponding deployment preview (will be) available at: [gh-pages](/bioimage-io/collection-bioimage-io/tree/gh-pages/resources/10.5281/zenodo.5910854)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO Spec validator (static validation);
- [ ] Passed the BioImage.IO CI tests (dynamic validations);
- [ ] The meta information for the RDF item is complete;
  - [ ] The tags is complete and describes the model;
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D);
  - [ ] Authors are provided;
  - [ ] Documentation is complete;
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: none specified

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Edit the current resource.yaml and mark the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Merge this PR for now, wait until the CI on the main branch to complete. It should detect the new versions and create another PR for the new version. You can take it from there instead.

### CODE REVIEW

**Comment by oeway** [comment]
@constantinpape Let's use this model for use case 3. I included onnx and torch script.

@esgomezm Could you check if you can get this model work with deepimagej? It take an image as input and produce a classes and a feature vector.

**Comment by FynnBe** [comment]
> The validation here fails with some errors I don't understand. Can you have a look @FynnBe?

same error as in #264 I'm on it...

**Comment by oeway** [comment]
@FynnBe FYI: If I close the PR, the CI runs but it doesn't give me a new PR with the new version.

**Comment by FynnBe** [comment]
isn't this the new version: https://github.com/bioimage-io/collection-bioimage-io/pull/267 ? it has the same resource_id..

**Pull request merged**
