### PR TITLE
Update CebraNET Cellular Membranes in Volume SEM

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.7274275.
The following version(s) will be added:
  - [7274276 (version 1)](https://www.doi.org/10.5281/zenodo.7274276)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [x] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [x] The meta information for the RDF item is complete
  - [x] The tags are complete and describe the model
  - [x] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [x] Authors are provided
  - [x] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [x] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @jhennies

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: none

### CODE REVIEW

**Comment by jhennies** [comment]
Is the model.eval() performed here now (https://github.com/bioimage-io/core-bioimage-io-python/pull/301)? The failed check shows quite a high difference between actual and expected output. Local validation is working fine when using ```bioimageio test-model model.zip --decimal 3```

**Comment by constantinpape** [comment]
Thanks @jhennies. The CI error is due to the issue with eval that is not in the release yet. We'll look into drafting the release soon and then this should be fixed.

**Comment by jhennies** [comment]
Great, thanks!

**Comment by constantinpape** [comment]
Ok, now we have the new version here and the test failure is only because it does not pass up to 4 decimals.
@FynnBe @oeway do you remember how to specify lower test precision in the `rdf.yaml:config`?

**Comment by FynnBe** [comment]
> Ok, now we have the new version here and the test failure is only because it does not pass up to 4 decimals. @FynnBe @oeway do you remember how to specify lower test precision in the `rdf.yaml:config`?

like so:
```yaml
config:
  bioimageio:
    test_kwargs:
      onnx:
        decimal: 2
      torchscript:
        decimal: 2

```

**Comment by constantinpape** [comment]
I forgot that we could just add this on the fly here @FynnBe, thanks!

Now reproducing the test output passes, but we still have the following error:
```
   {'bioimageio_core_version': '0.5.7',
   'bioimageio_spec_version': '0.4.8post1',
   'error': 'https://bioimage-io.github.io/collection-bioimage-io/rdfs/10.5281/zenodo.7274275/7274276/rdf.yaml',
   'id': 'validation_summary_pytorch_state_dict',
   'name': 'All URLs and paths available',
   'nested_errors': None,
   'source_name': '10.5281/zenodo.7274275/7274276',
   'status': 'failed',
   'traceback': ['  File '
                 '"/usr/share/miniconda/envs/7274276/lib/python3.10/site-packages/bioimageio/core/resource_tests.py", '
                 'line 87, in _test_resource_urls\n'
                 '    SourceNodeChecker(root_path=rd.root_path).visit(rd)\n',
                 '  File '
                 '"/usr/share/miniconda/envs/7274276/lib/python3.10/site-packages/bioimageio/spec/shared/node_transformer.py", '
                 'line 34, in visit\n'
                 '    visitor(node)\n',
                 '  File '
                 '"/usr/share/miniconda/envs/7274276/lib/python3.10/site-packages/bioimageio/spec/shared/node_transformer.py", '
                 'line 41, in generic_visit\n'
                 '    self.visit(value)\n',
                 '  File '
                 '"/usr/share/miniconda/envs/7274276/lib/python3.10/site-packages/bioimageio/spec/shared/node_transformer.py", '
                 'line 34, in visit\n'
                 '    visitor(node)\n',
                 '  File '
                 '"/usr/share/miniconda/envs/7274276/lib/python3.10/site-packages/bioimageio/core/resource_io/utils.py", '
                 'line 38, in visit_URI\n'
                 '    self._visit_source(node)\n',
                 '  File '
                 '"/usr/share/miniconda/envs/7274276/lib/python3.10/site-packages/bioimageio/core/resource_io/utils.py", '
                 'line 35, in _visit_source\n'
                 '    raise FileNotFoundError(leaf)\n'],
   'warnings': {}},
```
Any idea what causes this? (I guess some file is not found, but the error message is fairly cryptic...)

**Comment by FynnBe** [comment]
> Any idea what causes this? (I guess some file is not found, but the error message is fairly cryptic...)

I actually don't quite understand why we don't have this error all the time... Probably it just appears now due to a new core release... 

The issue is that we specify the `rdf_source` for all rdfs in the collection explicitly here:
https://github.com/bioimage-io/collection-bioimage-io/blob/e81e6311dc27834c1eb8c56336144b931c767e4f/scripts/utils.py#L272

This only holds true if the model is merged and thus actually deployed to gh-pages and then by the gh-pages action to this deployment url... 
so for accepted models this is a reasonable test, but for these candidates it will always fail. 
Maybe the best is to knowingly ignore this particular error here in collection (check if that particular test starts with the gh-deployment url)....

Let me quickly abuse this PR for this...

**Comment by FynnBe** [comment]
ahh.. of course the CI runs with the main gh workflows not the updated ones from here.. I'll move the CI change to a separete PR...

**Comment by constantinpape** [comment]
The error still persists despite having merged the changes from #500 @FynnBe

**Review by constantinpape — APPROVED** [review]
@jhennies this is good to go from our side now. Should we merge it, or do you want to change something else?

(One thing that could still be added is a `Validation` section to the docs, which describes how to validate that the model outptus should be validated, but we can do this in an updated version of the model once the publication is there.)

**Comment by jhennies** [comment]
> @jhennies this is good to go from our side now. Should we merge it, or do you want to change something else?
> 
> (One thing that could still be added is a `Validation` section to the docs, which describes how to validate that the model outptus should be validated, but we can do this in an updated version of the model once the publication is there.)

Let's go ahead for now, I am pretty sure that there will be something else that comes up as well when it gets closer to the publication. So please do the merge! 

And thanks @FynnBe and @constantinpape for getting it to work!

**Comment by constantinpape** [comment]
> just noticed that the documentation (https://zenodo.org/api/files/c95661ca-b06a-464f-810c-5c9804ebe982/README.md) is actually written in html... @constantinpape if we accept this shouldn't we update the spec then and allow `.html` suffixes?

I didn't actually check the doc carefully because of #501. Whether we can support `html` depends on we can render it on the website (but doesn't look like it: https://bioimage.io/#/?tags=joyful-deer&id=10.5281%2Fzenodo.7274275).

@oeway would html rendering be possible for the model cards? Only if this is easy for you, if not we can just demand that it's markdown and change it for the model here; from now on we should check the documentation better (#501 will help with it).

**Comment by FynnBe** [comment]
We should also keep in mind that other user software might want to display the documentation (e.g. for a loaded model). Keeping it simple and sticking to markdown only might be a good idea...

**Comment by constantinpape** [comment]
> We should also keep in mind that other user software might want to display the documentation (e.g. for a loaded model). Keeping it simple and sticking to markdown only might be a good idea...

Yes, good point. Let's stick with markdown only.

@FynnBe: can we somehow check this more explicitly? (If not I think this is not so important if we have #501 working, then it's easy to check manually).
@jhennies: can you prepare a markdown version of the doc for the next version of this model?

**Comment by FynnBe** [comment]
> @FynnBe: can we somehow check this more explicitly? (If not I think this is not so important if we have #501 working, then it's easy to check manually).

Quick google search gave me a promising hit: https://marko-py.readthedocs.io/en/latest/
Marko also supports github flavored md: https://marko-py.readthedocs.io/en/latest/extensions.html#github-flavored-markdown
Would we want vanilla markdown or allow github falvored right away (pro: we are very github centric already, con: already includes some html tags, etc, which makes it harder for software)
Maybe we can support gh md, if there is an easy way to 'clean' such md file?

**Comment by jhennies** [comment]
> @jhennies: can you prepare a markdown version of the doc for the next version of this model?

Yes, I fixed that for the next version. Actually a mistake on my side that I didn't double check, the URL to the README.md was wrong

**Pull request merged**
