### PR TITLE
QuPath added to partner list

### PR DESCRIPTION
**Pull request by IvanHCenalmor**

### CODE REVIEW

**Comment by esgomezm** [comment]
Hi! I see everything correct with respect to QuPath. However, there are some issues with ImJoy and models in the static validation. @FynnBe and @oeway any idea why this is not working?

**Comment by oeway** [comment]
@IvanHCenalmor Could you add me (@oeway) as collaborator of the qupath-bioimage-io repo? Thank you! This will make it easier for us to help you maintaining your collection, and keep synchronised in case we make changes to the specification. We also do this for other partners. 

For the CI issues, @FynnBe could you look into it? I don't know what's going on, I didn't change anything to imjoy recently.

**Comment by esgomezm** [comment]
hi @oeway 
> @IvanHCenalmor Could you add me (@oeway) as collaborator of the qupath-bioimage-io repo? Thank you! This will make it easier for us to help you maintaining your collection, and keep synchronised in case we make changes to the specification. We also do this for other partners.

I guess it is @petebankhead the one who has to give access ;)

**Comment by FynnBe** [comment]
The CI failure here is due to a partial bugfix I pushed on Monday...
The remaining part of this issue are some models in the deepimagej collection: https://github.com/deepimagej/models/issues/48

I propose to add validation for the qupath collection directly in the qupath collection repo (as all partners have): https://github.com/qupath/qupath-bioimage-io/pull/2

**Comment by FynnBe** [comment]
the CI rerun failed due to GH rate limitations... I'll give it a go again later, but we can also just merge this. the change looks good 👍 and in the previous run all errors were deepimagej or fiji related (I fixed the fiji one https://github.com/bioimage-io/fiji-bioimage-io/pull/3)

**Pull request merged**
