### PR TITLE
Update HPA Bestfitting InceptionV3

### PR DESCRIPTION
**Pull request by bioimageiobot**
This is an automatic PR created by the @bioimageiobot regarding changes to the resource item 10.5281/zenodo.5910854.
The following version(s) will be added:
  - [6539073 (version 3)](https://www.doi.org/10.5281/zenodo.6539073)

Please review the changes and make sure the new item or version(s) pass the following check list:
- [ ] Passed the BioImage.IO CI tests: static (and dynamic) validations
- [ ] The meta information for the RDF item is complete
  - [ ] The tags are complete and describe the model
  - [ ] Naming is intuitive and descriptive, example:  Multi-Organ Nucleus Segmentation (StarDist 2D)
  - [ ] Authors are provided
  - [ ] Documentation is complete
    * For models, include an overview, describe how the model is trained, what is the training data, how to use the model, how to validate the results and list the references. TODO: Model documentation template.
- [ ] Approved by at least one of the BioImage.IO admin team member.

Maintainers: @oeway

Note: If you updated or re-uploaded another version for the current item on Zenodo, this PR won't be changed automatically. To proceed, you can do the following:
 1. Block this version, but keep looking for future versions: Edit the current resource.yaml and keep the top-level `status` field as `accepted`, but change the `status` under the current version to `blocked`.
 2. Accept this version and keep looking for future versions: Merge this PR for now.
 3. Keep proposed version(s) (and this resource in general if it is new) as pending: Close this PR without merging.

 Then wait for the CI on the main branch to complete. It should detect the new version(s) and create another PR for the new version(s).

Previous PRs of this resource: https://github.com/bioimage-io/collection-bioimage-io/pull/300

### CODE REVIEW

**Comment by oeway** [comment]
@constantinpape Do we already have an option for setting the tolerance? https://github.com/bioimage-io/collection-bioimage-io/runs/6388418726?check_suite_focus=true

**Comment by constantinpape** [comment]
> @constantinpape Do we already have an option for setting the tolerance? https://github.com/bioimage-io/collection-bioimage-io/runs/6388418726?check_suite_focus=true

Good question. It's definitely possible to set it for the test function, but I am not sure if we have a way to pass it to the CI.
Any ideas @FynnBe?

**Comment by FynnBe** [comment]
yes, like we did for this model's previous version

**Comment by constantinpape** [comment]
@FynnBe @oeway it looks now like validation fails because some URL is not available. Could you double check this?

**Comment by FynnBe** [comment]
I'll look into it

**Comment by FynnBe** [comment]
so, very confusing, the latest version 3 of this resource has the wrong doi in its rdf.yaml:config field
[6539073 (version 3)](https://www.doi.org/10.5281/zenodo.6539073)
so looking at that doi I added the test kwargs to the old version..

**Comment by oeway** [comment]
> so, very confusing, the latest version 3 of this resource has the wrong doi in its rdf.yaml:config field [6539073 (version 3)](https://www.doi.org/10.5281/zenodo.6539073) so looking at that doi I added the test kwargs to the old version..

I guess this is what happens when we use the edit button on the website? We need to maybe remove the id before uploading, would that help?

**Comment by FynnBe** [comment]
> I guess this is what happens when we use the edit button on the website? We need to maybe remove the id before uploading, would that help?

Sounds about right. 👍

**Comment by FynnBe** [comment]
> @FynnBe @oeway it looks now like validation fails because some URL is not available. Could you double check this?

btw, this was a sporadic zenodo 500

**Comment by oeway** [comment]
> 

If it's 500, not much we can do, it's zenodo internal server error.

**Comment by oeway** [comment]
Looks like this all passes, merging now

**Pull request merged**
